/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Fabri
 */
import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Gato;
import modelo.Hogar_Adopcion;
import modelo.Usuario;
import modelo.Familia;
import modelo.Voluntario; 
import servicio.Swingcontexto;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.GridLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import java.awt.Dimension;
import vista.VerSolicitudes;

public class PanelAdopcion extends javax.swing.JPanel {
    private Swingcontexto servicios;
    private Usuario usuarioLogueado;
    private DefaultTableModel modeloTabla;
    private static final DateTimeFormatter FORMATO_FECHA = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
    /**
     * Creates new form PanelAdopcion
     */
    public PanelAdopcion(Swingcontexto servicios, Usuario usuarioLogueado) {
        this.servicios = servicios;
        this.usuarioLogueado = usuarioLogueado;
        initComponents();
        configurarTabla();
        cargarDatosTabla(servicios.adopcionService.listarGatosDisponibles());
        
    }
    private void configurarTabla() {
        modeloTabla = new DefaultTableModel() {
            @Override public boolean isCellEditable(int row, int column) { return false; }
        };
        modeloTabla.addColumn("ID Gato");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Color");
        modeloTabla.addColumn("Zona");
        modeloTabla.addColumn("Estado Adopción");
        modeloTabla.addColumn("Apto");
        
        tablaAdopciones.setModel(modeloTabla);
    }
    private void cargarDatosTabla(List<Gato> gatos) {
        modeloTabla.setRowCount(0); 
        
        for (Gato gato : gatos) {
            Object[] fila = {
                gato.getId(),
                gato.getNombre(),
                gato.getColor(),
                (gato.getZona() != null) ? gato.getZona().getNombrezona() : "N/A",gato.getAdoptado(),(gato.getApto() == 1) ? "Si" : "No"};
            modeloTabla.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adopscroll = new javax.swing.JScrollPane();
        tablaAdopciones = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        BUSCARID = new javax.swing.JTextField();
        REGISTRO_MANUAL = new javax.swing.JButton();
        CANCELAR = new javax.swing.JButton();
        DISPONIBLES = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ADOPTADOS = new javax.swing.JButton();
        POR_FAMILIA = new javax.swing.JButton();
        ACTLISTA = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BUSCAR = new javax.swing.JButton();
        Versolis = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CENTRO DE ADOPCIONES", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N
        setLayout(new java.awt.BorderLayout());

        tablaAdopciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        adopscroll.setViewportView(tablaAdopciones);

        add(adopscroll, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("ID ADOPCION");

        BUSCARID.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        REGISTRO_MANUAL.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        REGISTRO_MANUAL.setText("REGISTRAR MANUAL");
        REGISTRO_MANUAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTRO_MANUALActionPerformed(evt);
            }
        });

        CANCELAR.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        CANCELAR.setText("CANCELAR ADOPCION");
        CANCELAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CANCELARActionPerformed(evt);
            }
        });

        DISPONIBLES.setText("DISPONIBLES");
        DISPONIBLES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DISPONIBLESActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel2.setText("Lista de adopciones");

        ADOPTADOS.setText("ADOPTADOS");
        ADOPTADOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADOPTADOSActionPerformed(evt);
            }
        });

        POR_FAMILIA.setText("POR FAMILIA");
        POR_FAMILIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                POR_FAMILIAActionPerformed(evt);
            }
        });

        ACTLISTA.setText("VER TODOS");
        ACTLISTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACTLISTAActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("Filtros");

        BUSCAR.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BUSCAR.setText("BUSCAR");
        BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCARActionPerformed(evt);
            }
        });

        Versolis.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Versolis.setText("VER SOLICITUDES");
        Versolis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VersolisActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(REGISTRO_MANUAL)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CANCELAR))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(3, 3, 3)
                                .addComponent(BUSCARID, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(Versolis, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(DISPONIBLES)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ADOPTADOS)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(POR_FAMILIA)
                                .addGap(18, 18, 18)
                                .addComponent(ACTLISTA))
                            .addComponent(jLabel3))
                        .addGap(23, 23, 23)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DISPONIBLES, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ADOPTADOS, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(POR_FAMILIA, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ACTLISTA, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(BUSCARID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BUSCAR))
                        .addGap(14, 14, 14)
                        .addComponent(Versolis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CANCELAR)
                            .addComponent(REGISTRO_MANUAL))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void DISPONIBLESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DISPONIBLESActionPerformed
        cargarDatosTabla(servicios.adopcionService.listarGatosDisponibles());
    }//GEN-LAST:event_DISPONIBLESActionPerformed

    private void ADOPTADOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADOPTADOSActionPerformed
        List<Gato> adoptados = servicios.adopcionService.mostrarGatosAdoptados();
        List<Gato> transicion = servicios.adopcionService.mostrarGatosTransicion();
        adoptados.addAll(transicion); 
        cargarDatosTabla(adoptados);
    }//GEN-LAST:event_ADOPTADOSActionPerformed

    private void POR_FAMILIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_POR_FAMILIAActionPerformed
         try {
            List<Hogar_Adopcion> hogares = servicios.gestionHogares.listarHogares();
            
            if (hogares.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay hogares registrados.", "Reporte", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            StringBuilder reporte = new StringBuilder();
            reporte.append("--- Reporte de Gatos por Familia ---\n\n");
            
            for (Hogar_Adopcion hogar : hogares) {
                Familia fam = hogar.getFamilia();
                reporte.append("Familia: " + (fam != null ? fam.getNombre() : "N/A") + " (Hogar ID: " + hogar.getIdhogarfam() + ")\n");
                List<Gato> gatos = hogar.getGatos(); 
                if (gatos == null || gatos.isEmpty()) {
                    reporte.append("  - Sin gatos asignados actualmente.\n");
                } else {
                    for (Gato gato : gatos) {
                        reporte.append("  - Gato: " + gato.getNombre() + " (ID: " + gato.getId() + ") | Estado: " + gato.getAdoptado() + "\n");
                    }
                }
                reporte.append("----------------------------------\n");
            }
            JTextArea textArea = new JTextArea(reporte.toString());
            textArea.setEditable(false);
            JScrollPane scrollPane = new JScrollPane(textArea);
            scrollPane.setPreferredSize(new Dimension(600, 450)); 

            JOptionPane.showMessageDialog(
                this, 
                scrollPane, 
                "Reporte: Gatos por Familia", 
                JOptionPane.INFORMATION_MESSAGE
            );

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al generar reporte: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_POR_FAMILIAActionPerformed

    private void ACTLISTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACTLISTAActionPerformed
        cargarDatosTabla(servicios.gatoService.listarGatos());
        BUSCARID.setText("");
    }//GEN-LAST:event_ACTLISTAActionPerformed

    private void REGISTRO_MANUALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTRO_MANUALActionPerformed
        JComboBox<Gato> cmbGatos = new JComboBox<>();
        List<Gato> gatosDisponibles = servicios.adopcionService.listarGatosDisponibles();
        DefaultComboBoxModel<Gato> gatoModel = new DefaultComboBoxModel<>();
        gatoModel.addElement(null);
        for(Gato g : gatosDisponibles) gatoModel.addElement(g);
        cmbGatos.setModel(gatoModel);
        cmbGatos.setRenderer(new GatoComboBoxRenderer());
        JComboBox<Hogar_Adopcion> cmbHogares = new JComboBox<>();
        List<Hogar_Adopcion> hogares = servicios.gestionHogares.listarHogaresPostulados();
        DefaultComboBoxModel<Hogar_Adopcion> hogarModel = new DefaultComboBoxModel<>();
        hogarModel.addElement(null);
        for(Hogar_Adopcion h : hogares) hogarModel.addElement(h);
        cmbHogares.setModel(hogarModel);
        cmbHogares.setRenderer(new HogarComboBoxRenderer());
        JComboBox<String> cmbTipo = new JComboBox<>(new String[]{"Seleccione una opcion", "Temporal (Transicion)", "Definitiva"});
        JPanel dialogPanel = new JPanel(new GridLayout(3, 2, 5, 5));
        dialogPanel.add(new JLabel("Gato a adoptar:"));
        dialogPanel.add(cmbGatos);
        dialogPanel.add(new JLabel("Hogar (Familia):"));
        dialogPanel.add(cmbHogares);
        dialogPanel.add(new JLabel("Tipo de Adopcion:"));
        dialogPanel.add(cmbTipo);
        int result = JOptionPane.showConfirmDialog(this, dialogPanel, "Registrar Adopcion Manual",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            try {
                Gato gato = (Gato) cmbGatos.getSelectedItem();
                Hogar_Adopcion hogar = (Hogar_Adopcion) cmbHogares.getSelectedItem();
                int tipo = cmbTipo.getSelectedIndex(); 
                
                servicios.adopcionService.realizarAdopcion(gato, hogar, tipo);
                
                JOptionPane.showMessageDialog(this, "Adopcion registrada", "exito", JOptionPane.INFORMATION_MESSAGE);
                cargarDatosTabla(servicios.adopcionService.listarGatosDisponibles());

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al registrar adopcion: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_REGISTRO_MANUALActionPerformed

    private void CANCELARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CANCELARActionPerformed
        int filaSel = tablaAdopciones.getSelectedRow();
        if (filaSel == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un gato de la tabla para cancelar su adopcion.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int idGato = (int) modeloTabla.getValueAt(filaSel, 0);
        try {
            Gato gato = servicios.gatoService.buscarGatoID(idGato);
            if (gato == null) throw new Exception("Gato no encontrado.");
            if (gato.getHogar() == null) throw new Exception("Este gato no esta asignado a ningun hogar.");
            
            Hogar_Adopcion hogar = gato.getHogar();
            
            int confirm = JOptionPane.showConfirmDialog(this, "Seguro que deseas cancelar la adopcion de '" + gato.getNombre() + "' del hogar de la familia '" + hogar.getFamilia().getNombre() + "'?","Confirmar Cancelacion", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if (confirm == JOptionPane.YES_OPTION) {
                servicios.adopcionService.cancelarAdopcion(gato, hogar);
                JOptionPane.showMessageDialog(this, "Adopcion cancelada. El gato esta 'Libre'.", "exito", JOptionPane.INFORMATION_MESSAGE);
                cargarDatosTabla(servicios.adopcionService.listarGatosDisponibles());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cancelar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_CANCELARActionPerformed

    private void BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSCARActionPerformed
        try {
            String idStr = BUSCARID.getText().trim();
            
            if (idStr.isEmpty()) {
                throw new Exception("ingrese un ID de Gato para buscar.");
            }
            int idGato = Integer.parseInt(idStr);
            Gato gato = servicios.gatoService.buscarGatoID(idGato);
            
            if (gato != null) {
                List<Gato> listaBusqueda = new ArrayList<>();
                listaBusqueda.add(gato);
                cargarDatosTabla(listaBusqueda); 
            } else {
                JOptionPane.showMessageDialog(this, "No se encontro ningún gato con el ID: " + idGato, "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ingrese un ID valido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error al Buscar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BUSCARActionPerformed

    private void VersolisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VersolisActionPerformed
        if (usuarioLogueado.getRol() != 1 && usuarioLogueado.getRol() != 3) {
            JOptionPane.showMessageDialog(this, "No tienes permisos para ver solicitudes.", "Acceso Denegado", JOptionPane.ERROR_MESSAGE);
            return;
        }
        VerSolicitudes panelPopUp = new VerSolicitudes(servicios, usuarioLogueado);
        panelPopUp.setPreferredSize(new Dimension(700, 400));
        JOptionPane.showMessageDialog(this, panelPopUp, "Solicitudes de Adopcion Pendientes",  JOptionPane.PLAIN_MESSAGE );
        cargarDatosTabla(servicios.adopcionService.listarGatosDisponibles());
    }//GEN-LAST:event_VersolisActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACTLISTA;
    private javax.swing.JButton ADOPTADOS;
    private javax.swing.JButton BUSCAR;
    private javax.swing.JTextField BUSCARID;
    private javax.swing.JButton CANCELAR;
    private javax.swing.JButton DISPONIBLES;
    private javax.swing.JButton POR_FAMILIA;
    private javax.swing.JButton REGISTRO_MANUAL;
    private javax.swing.JButton Versolis;
    private javax.swing.JScrollPane adopscroll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable tablaAdopciones;
    // End of variables declaration//GEN-END:variables
}
