/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Fabri
 */
import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Gato;
import servicio.Swingcontexto; 
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.GridLayout;
import modelo.Zona_geografica;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import java.awt.Dimension;
import java.awt.event.ItemEvent;
import modelo.Usuario;
import javax.swing.ImageIcon; 
import java.awt.Image;


public class PanelGestionGatos extends javax.swing.JPanel {
    private Swingcontexto servicios;
    private Usuario usuarioLogueado;
    private DefaultTableModel modeloTabla;
    /**
     * Creates new form PanelGestionGatos
     */
    public PanelGestionGatos(Swingcontexto servicios,Usuario usuarioLogueado) {
        this.servicios = servicios;
        this.usuarioLogueado = usuarioLogueado;
        initComponents();
        configurarTabla();
        cargarZonasComboBox(); 
        cargarDatosTabla(servicios.gatoService.listarGatos());
        if (usuarioLogueado.getRol() != 1) {
           REPORTE.setVisible(false);
        }
    }
    private void configurarTabla() {
        modeloTabla = new DefaultTableModel() {
            @Override public boolean isCellEditable(int row, int column) { return false; }
        };
        
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Color");
        modeloTabla.addColumn("Zona");
        modeloTabla.addColumn("Estado Adopcion");
        modeloTabla.addColumn("Apto");
        tablaGatos.setModel(modeloTabla); 
    }
    private void cargarDatosTabla(List<Gato> gatos) {
        modeloTabla.setRowCount(0); 
        for (Gato gato : gatos) {
            Object[] fila = {
                gato.getId(),
                gato.getNombre(),
                gato.getColor(),
                (gato.getZona() != null) ? gato.getZona().getNombrezona() : "N/A",
                gato.getAdoptado(),
                (gato.getApto() == 1) ? "Sí" : "No"
            };
            modeloTabla.addRow(fila);
        }
    }
    private void cargarZonasComboBox() {
     
        List<Zona_geografica> zonas = servicios.zonaService.listarZonas();
        DefaultComboBoxModel<Zona_geografica> comboModel = new DefaultComboBoxModel<>();
        
        comboModel.addElement(null); 
        for (Zona_geografica zona : zonas) {
            comboModel.addElement(zona); 
        }
        cmbZonas.setRenderer(new ZonaComboBoxRenderer());
        cmbZonas.setModel(comboModel);
    }
    private void limpiarFiltros() {
        ins_id.setText("");
        cmbZonas.setSelectedIndex(0); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        MODIFICAR = new javax.swing.JButton();
        cmbZonas = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        ins_id = new javax.swing.JTextField();
        Buscar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Disponibles = new javax.swing.JButton();
        Registrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        REPORTE = new javax.swing.JButton();
        VER_QR = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaGatos = new javax.swing.JTable();
        ACT = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GESTOR GATOS", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N

        MODIFICAR.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        MODIFICAR.setText("Modificar Gato");
        MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFICARActionPerformed(evt);
            }
        });

        cmbZonas.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cmbZonas.setMaximumRowCount(10);
        cmbZonas.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbZonasItemStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("ID:");

        ins_id.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ins_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ins_idActionPerformed(evt);
            }
        });

        Buscar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Buscar.setText("Buscar Gato");
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });

        Eliminar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Eliminar.setText("Eliminar Gato");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Disponibles.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Disponibles.setText("Mostrar disponibles");
        Disponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisponiblesActionPerformed(evt);
            }
        });

        Registrar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        Registrar.setText("Registrar Gato");
        Registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel3.setText("ZONA");

        REPORTE.setText("<html><center>GENERAR<br>REPORTE</center></html>");
        REPORTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REPORTEActionPerformed(evt);
            }
        });

        VER_QR.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        VER_QR.setText("VER QR");
        VER_QR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VER_QRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ins_id, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Buscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbZonas, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(VER_QR))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Disponibles)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MODIFICAR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(REPORTE, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(ins_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Buscar)
                            .addComponent(jLabel3)
                            .addComponent(cmbZonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(VER_QR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Registrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Disponibles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Eliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MODIFICAR))
                        .addContainerGap())
                    .addComponent(REPORTE, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        tablaGatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaGatos);

        ACT.setText("<html><center>ACTUALIZAR<br>LISTA</center></html>");
        ACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ACT, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ACT, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 494, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void RegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarActionPerformed
        JTextField txtNombreDialog = new JTextField(); 
        JTextField txtColorDialog = new JTextField();
        JTextField txtDescripcionDialog = new JTextField();
        JComboBox<Zona_geografica> cmbZonasDialog = new JComboBox<>();
        JTextField txtEdad = new JTextField("0");
        JTextField txtFotoUrl = new JTextField();
        List<Zona_geografica> zonas = servicios.zonaService.listarZonas();
        DefaultComboBoxModel<Zona_geografica> comboModel = new DefaultComboBoxModel<>();
        comboModel.addElement(null); 
        for(Zona_geografica z : zonas) {
            comboModel.addElement(z);
        }
        cmbZonasDialog.setModel(comboModel);
        cmbZonasDialog.setRenderer(new ZonaComboBoxRenderer());
        if (cmbZonas.getSelectedItem() instanceof Zona_geografica) {
            cmbZonasDialog.setSelectedItem(cmbZonas.getSelectedItem());
        }
        JPanel dialogPanel = new JPanel(new GridLayout(6, 2, 5, 5));
        dialogPanel.add(new JLabel("Nombre:"));
        dialogPanel.add(txtNombreDialog);
        dialogPanel.add(new JLabel("Color:"));
        dialogPanel.add(txtColorDialog);
        dialogPanel.add(new JLabel("Descripcion:"));
        dialogPanel.add(txtDescripcionDialog);
        dialogPanel.add(new JLabel("Zona:"));
        dialogPanel.add(cmbZonasDialog);
        dialogPanel.add(new JLabel("Edad (en meses):"));
        dialogPanel.add(txtEdad);
        dialogPanel.add(new JLabel("Foto (URL):"));
        dialogPanel.add(txtFotoUrl);
        int result = JOptionPane.showConfirmDialog(
                this, dialogPanel, "Registrar Nuevo Gato",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE
        );
        if (result == JOptionPane.OK_OPTION) {
            try {
                String nombre = txtNombreDialog.getText();
                String color = txtColorDialog.getText();
                String descripcion = txtDescripcionDialog.getText();
                Zona_geografica zonaSel = (Zona_geografica) cmbZonasDialog.getSelectedItem();
                int edad = Integer.parseInt(txtEdad.getText()); 
                String fotoUrl = txtFotoUrl.getText();
                servicios.gatoService.registrarGatos(nombre, color, descripcion, zonaSel, edad, fotoUrl);
                JOptionPane.showMessageDialog(this, "Gato registrado", "exito", JOptionPane.INFORMATION_MESSAGE);
                cargarDatosTabla(servicios.gatoService.listarGatos()); 
                limpiarFiltros();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al registrar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_RegistrarActionPerformed

    private void DisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisponiblesActionPerformed

        List<Gato> disponibles = servicios.gatoService.listarGatosDisponibles();
        cargarDatosTabla(disponibles);
    }//GEN-LAST:event_DisponiblesActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed

        int filaSeleccionada = tablaGatos.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un gato de la tabla para eliminar", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int idGato = (int) modeloTabla.getValueAt(filaSeleccionada, 0); 
        String nombreGato = (String) modeloTabla.getValueAt(filaSeleccionada, 1); 

        int confirm = JOptionPane.showConfirmDialog(this,"Seguro que deseas eliminar a " + nombreGato + " (ID: " + idGato + ")?","Confirmar Eliminación",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                Gato gato = servicios.gatoService.buscarGatoID(idGato);
                servicios.gatoService.eliminarGato(gato);
                JOptionPane.showMessageDialog(this, "Gato eliminado.", "exito", JOptionPane.INFORMATION_MESSAGE);
                cargarDatosTabla(servicios.gatoService.listarGatos());

            } catch (Exception e) {

                JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_EliminarActionPerformed

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        try {

            int id = Integer.parseInt(ins_id.getText());
            Gato g = servicios.gatoService.buscarGatoID(id);

            if (g != null) {
                List<Gato> listaBusqueda = new ArrayList<>();
                listaBusqueda.add(g);
                cargarDatosTabla(listaBusqueda);
            } else {
                JOptionPane.showMessageDialog(this, "No se encontro ningun gato con el ID: " + id, "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Ingrese un ID valido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BuscarActionPerformed

    private void ins_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ins_idActionPerformed
        BuscarActionPerformed(evt);
    }//GEN-LAST:event_ins_idActionPerformed

    private void MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFICARActionPerformed

        int filaSeleccionada = tablaGatos.getSelectedRow();
        if (filaSeleccionada == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un gato de la tabla para modificar", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int idGato = (int) modeloTabla.getValueAt(filaSeleccionada, 0);
        Gato gatoAModificar = servicios.gatoService.buscarGatoID(idGato);

        if (gatoAModificar == null) {
            JOptionPane.showMessageDialog(this, "No se pudo encontrar el gato seleccionado en la base de datos.", "Error", JOptionPane.ERROR_MESSAGE);
            cargarDatosTabla(servicios.gatoService.listarGatos());
            return;
        }
        JTextField txtNombre = new JTextField(gatoAModificar.getNombre());
        JTextField txtColor = new JTextField(gatoAModificar.getColor());
        JTextField txtDescripcion = new JTextField(gatoAModificar.getDescripcion());
        JComboBox<Zona_geografica> cmbZonasDialog = new JComboBox<>();
        JTextField txtEdad = new JTextField(String.valueOf(gatoAModificar.getEdad()));
        JTextField txtFotoUrl = new JTextField(gatoAModificar.getFotoUrl());

        List<Zona_geografica> zonas = servicios.zonaService.listarZonas();
        DefaultComboBoxModel<Zona_geografica> comboModel = new DefaultComboBoxModel<>();
        comboModel.addElement(null);
        for(Zona_geografica z : zonas) {
            comboModel.addElement(z);
        }
        cmbZonasDialog.setModel(comboModel);
        cmbZonasDialog.setRenderer(new ZonaComboBoxRenderer());

        cmbZonasDialog.setSelectedItem(gatoAModificar.getZona()); //zona actual

        JPanel dialogPanel = new JPanel(new GridLayout(6, 2, 5, 5));
        dialogPanel.add(new JLabel("Nombre:"));
        dialogPanel.add(txtNombre);
        dialogPanel.add(new JLabel("Color:"));
        dialogPanel.add(txtColor);
        dialogPanel.add(new JLabel("Descripcion:"));
        dialogPanel.add(txtDescripcion);
        dialogPanel.add(new JLabel("Zona:"));
        dialogPanel.add(cmbZonasDialog);
        dialogPanel.add(new JLabel("Edad (meses):"));
        dialogPanel.add(txtEdad);
        dialogPanel.add(new JLabel("Foto (URL):"));
        dialogPanel.add(txtFotoUrl);

        int result = JOptionPane.showConfirmDialog(
            this, dialogPanel, "Modificar Gato (ID: " + idGato + ")",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE
        );
        if (result == JOptionPane.OK_OPTION) {
            try {
                String nuevoNombre = txtNombre.getText();
                String nuevoColor = txtColor.getText();
                String nuevaDescripcion = txtDescripcion.getText();
                Zona_geografica nuevaZona = (Zona_geografica) cmbZonasDialog.getSelectedItem();
                int nuevaEdad = Integer.parseInt(txtEdad.getText());
                String nuevaFotoUrl = txtFotoUrl.getText();
                servicios.gatoService.actualizarGato(gatoAModificar, nuevoNombre, nuevoColor, nuevaDescripcion, nuevaZona,nuevaEdad, nuevaFotoUrl);

                JOptionPane.showMessageDialog(this, "Gato modificado con exito", "exito", JOptionPane.INFORMATION_MESSAGE);
                cargarDatosTabla(servicios.gatoService.listarGatos());

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al modificar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_MODIFICARActionPerformed

    private void REPORTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REPORTEActionPerformed
       try {
            String reporte = servicios.gestorReportes.verReporteGeneral();
            JTextArea textArea = new JTextArea(reporte);
            textArea.setEditable(false);
            textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 12));
            JScrollPane scrollPane = new JScrollPane(textArea);
            scrollPane.setPreferredSize(new Dimension(600, 500)); 
            JOptionPane.showMessageDialog(this, scrollPane, "Reporte General de Gatos", JOptionPane.INFORMATION_MESSAGE
            );

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al generar el reporte: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_REPORTEActionPerformed

    private void cmbZonasItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbZonasItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            
            if (!ins_id.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Borra el campo 'ID' antes de filtrar por zona.", "Conflicto de Busqueda", JOptionPane.WARNING_MESSAGE);
                cmbZonas.setSelectedIndex(0); 
                cargarDatosTabla(servicios.gatoService.listarGatos());
                return;
            }
            Object item = cmbZonas.getSelectedItem();
            if (item instanceof Zona_geografica) {
                Zona_geografica zonaSel = (Zona_geografica) item;
                List<Gato> gatosFiltrados = servicios.gestorReportes.gatoporZona(zonaSel);
                cargarDatosTabla(gatosFiltrados);
            } else {
                cargarDatosTabla(servicios.gatoService.listarGatos());
            }
        }
    }//GEN-LAST:event_cmbZonasItemStateChanged

    private void ACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACTActionPerformed
        cargarDatosTabla(servicios.gatoService.listarGatos());
        ins_id.setText("");
        cmbZonas.setSelectedIndex(0);
    }//GEN-LAST:event_ACTActionPerformed

    private void VER_QRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VER_QRActionPerformed
        try {
            int filaSeleccionada = tablaGatos.getSelectedRow();
                if (filaSeleccionada == -1) {
                    throw new Exception("Seleccione un gato de la tabla.");
                }
                int idGato = (int) modeloTabla.getValueAt(filaSeleccionada, 0); 
                Gato gato = servicios.gatoService.buscarGatoID(idGato);
                    if (gato == null) {
                        throw new Exception("Gato no encontrado.");
                    }
                    String qrPath = gato.getQrUrl();
                        if (qrPath == null || qrPath.trim().isEmpty()) {
                            throw new Exception("Este gato no tiene un codigo QR registrado.");
                        }
                        ImageIcon qrIcon = new ImageIcon(qrPath);
                        Image image = qrIcon.getImage();
                        Image scaledImage = image.getScaledInstance(250, 250, Image.SCALE_SMOOTH); 
                        JLabel qrLabel = new JLabel(qrIcon);
            JOptionPane.showMessageDialog(this, qrLabel, "Codigo QR de " + gato.getNombre(), JOptionPane.INFORMATION_MESSAGE );
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error al ver QR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_VER_QRActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACT;
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Disponibles;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton MODIFICAR;
    private javax.swing.JButton REPORTE;
    private javax.swing.JButton Registrar;
    private javax.swing.JButton VER_QR;
    private javax.swing.JComboBox<modelo.Zona_geografica> cmbZonas;
    private javax.swing.JTextField ins_id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaGatos;
    // End of variables declaration//GEN-END:variables
class ZonaComboBoxRenderer extends javax.swing.plaf.basic.BasicComboBoxRenderer {
    @Override
    public java.awt.Component getListCellRendererComponent(
            javax.swing.JList list, Object value, int index,
            boolean isSelected, boolean cellHasFocus) {
        
        super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

        if (value instanceof Zona_geografica) {
            Zona_geografica zona = (Zona_geografica) value;
            setText(zona.getNombrezona() + " (ID: " + zona.getIdzona() + ")");
        } else if (value == null) {
            setText("Seleccione una zona");
        }
        return this;
    }
}
}
