/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Fabri
 */
import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Zona_geografica;
import servicio.Swingcontexto;
import servicio.Listado_zonas; 
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.GridLayout;
import javax.swing.DefaultComboBoxModel;

public class PanelZonas extends javax.swing.JPanel {
    private Swingcontexto servicios;
    private DefaultTableModel modeloTabla;
    /**
     * Creates new form PanelZonas
     */
    public PanelZonas(Swingcontexto servicios) {
        this.servicios = servicios;
        initComponents();
        configurarTabla();
        cargarDatosTabla();
    }
    private void configurarTabla() {
        modeloTabla = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; 
            }
        };

        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("Nombre de Zona");
        modeloTabla.addColumn("Coordenadas");
        modeloTabla.addColumn("Tipo");

        
        jTable1.setModel(modeloTabla);
    }
    private void cargarDatosTabla() {
        modeloTabla.setRowCount(0); 
        List<Zona_geografica> zonas = servicios.zonaService.listarZonas();

        for (Zona_geografica zona : zonas) {
            String tipoStr = switch (zona.getTipo()) {
                case 1 -> "Hogar";
                case 2 -> "Tarea";
                case 3 -> "Gato Encontrado";
                default -> "Desconocido";
            };
            
            Object[] fila = {
                zona.getIdzona(),
                zona.getNombrezona(),
                zona.getCoordenadas(),
                tipoStr
            };
            modeloTabla.addRow(fila);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        BUSCAR = new javax.swing.JButton();
        ELIMINAR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        MODIFICAR = new javax.swing.JButton();
        REGISTRAR = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GESTOR ZONAS", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        BUSCAR.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        BUSCAR.setText("BUSCAR");
        BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCARActionPerformed(evt);
            }
        });

        ELIMINAR.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ELIMINAR.setText("ELIMINAR");
        ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ELIMINARActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("ID");

        jTextField1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("NOMBRE_ZONA");

        MODIFICAR.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        MODIFICAR.setText("MODIFICAR");
        MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFICARActionPerformed(evt);
            }
        });

        REGISTRAR.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        REGISTRAR.setText("REGISTRAR ");
        REGISTRAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REGISTRARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(REGISTRAR)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BUSCAR))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(MODIFICAR)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ELIMINAR)))
                .addContainerGap(321, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUSCAR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(REGISTRAR)
                    .addComponent(MODIFICAR)
                    .addComponent(ELIMINAR))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 122, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFICARActionPerformed
        int filaSel = jTable1.getSelectedRow();
        if (filaSel == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una zona de la tabla para modificar.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int idZona = (int) modeloTabla.getValueAt(filaSel, 0);
        Zona_geografica zona = servicios.zonaService.buscarPorId(idZona);

        if (zona == null) {
            JOptionPane.showMessageDialog(this, "No se pudo encontrar la zona seleccionada.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        JTextField txtNombreZona = new JTextField(zona.getNombrezona());
        JTextField txtCoords = new JTextField(zona.getCoordenadas());
        JComboBox<String> cmbTipoDialog = new JComboBox<>(new String[]{"Hogar", "Tarea", "Gato Encontrado"});
        cmbTipoDialog.setSelectedIndex(zona.getTipo() - 1); 

        JPanel dialogPanel = new JPanel(new GridLayout(3, 2, 5, 5));
        dialogPanel.add(new JLabel("Nombre de Zona:"));
        dialogPanel.add(txtNombreZona);
        dialogPanel.add(new JLabel("Coordenadas:"));
        dialogPanel.add(txtCoords);
        dialogPanel.add(new JLabel("Tipo:"));
        dialogPanel.add(cmbTipoDialog);

        int result = JOptionPane.showConfirmDialog(this, dialogPanel, "Modificar Zona (ID: " + idZona + ")",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            try {
                String nuevoNombre = txtNombreZona.getText();
                String nuevasCoords = txtCoords.getText();
                int nuevoTipo = cmbTipoDialog.getSelectedIndex() + 1;

                
                servicios.zonaService.actualizarZona(idZona, nuevoNombre, nuevasCoords, nuevoTipo);
                
                JOptionPane.showMessageDialog(this, "Zona actualizada con exito.", "exito", JOptionPane.INFORMATION_MESSAGE);
                cargarDatosTabla(); 

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_MODIFICARActionPerformed

    private void ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ELIMINARActionPerformed
        int filaSel = jTable1.getSelectedRow();
        if (filaSel == -1) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar una zona de la tabla para eliminar.", "Error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        int idZona = (int) modeloTabla.getValueAt(filaSel, 0);
        String nombreZona = (String) modeloTabla.getValueAt(filaSel, 1);
        
        int confirm = JOptionPane.showConfirmDialog(this, 
            "Seguro que deseas eliminar la zona '" + nombreZona + "' (ID: " + idZona + ")?",
            "Confirmar Eliminación", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                Zona_geografica zona = servicios.zonaService.buscarPorId(idZona);
                servicios.zonaService.eliminarZona(zona);
                
                JOptionPane.showMessageDialog(this, "Zona eliminada con exito.", "exito", JOptionPane.INFORMATION_MESSAGE);
                cargarDatosTabla(); 
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_ELIMINARActionPerformed

    private void REGISTRARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REGISTRARActionPerformed

        JTextField txtNombreZona = new JTextField(jTextField1.getText()); 
        JTextField txtCoords = new JTextField();
        JComboBox<String> cmbTipoDialog = new JComboBox<>(new String[]{"Seleccione...", "Hogar", "Tarea", "Gato Encontrado"});

        JPanel dialogPanel = new JPanel(new GridLayout(3, 2, 5, 5));
        dialogPanel.add(new JLabel("Nombre de Zona:"));
        dialogPanel.add(txtNombreZona);
        dialogPanel.add(new JLabel("Coordenadas:"));
        dialogPanel.add(txtCoords);
        dialogPanel.add(new JLabel("Tipo:"));
        dialogPanel.add(cmbTipoDialog);

        int result = JOptionPane.showConfirmDialog(this, dialogPanel, "Registrar Nueva Zona",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

        if (result == JOptionPane.OK_OPTION) {
            try {
                String nombre = txtNombreZona.getText();
                String coords = txtCoords.getText();
                int tipo = cmbTipoDialog.getSelectedIndex(); 

                if (tipo == 0) {
                    throw new Exception("Debe seleccionar un tipo valido.");
                }
                servicios.zonaService.registrarZona(nombre, coords, tipo);
                
                JOptionPane.showMessageDialog(this, "Zona registrada con exito.", "exito", JOptionPane.INFORMATION_MESSAGE);
                cargarDatosTabla(); 
                
               
                jTextField1.setText("");
                jTextField2.setText("");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al registrar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_REGISTRARActionPerformed

    private void BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSCARActionPerformed
        try {
            String idStr = jTextField2.getText();
            if (idStr.trim().isEmpty()) {
                cargarDatosTabla();
                JOptionPane.showMessageDialog(this, "Mostrando todas las zonas.", "Busqueda", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            
            int id = Integer.parseInt(idStr);
            Zona_geografica zona = servicios.zonaService.buscarPorId(id);
            
            if (zona != null) {
                modeloTabla.setRowCount(0); 
                String tipoStr = switch (zona.getTipo()) {
                    case 1 -> "Hogar";
                    case 2 -> "Tarea";
                    case 3 -> "Gato Encontrado";
                    default -> "Desconocido";
                };
                Object[] fila = { zona.getIdzona(), zona.getNombrezona(), zona.getCoordenadas(), tipoStr };
                modeloTabla.addRow(fila);
                
            } else {
                JOptionPane.showMessageDialog(this, "No se encontro ninguna zona con el ID: " + id, "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ingrese un ID  valido", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BUSCARActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BUSCAR;
    private javax.swing.JButton ELIMINAR;
    private javax.swing.JButton MODIFICAR;
    private javax.swing.JButton REGISTRAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
