/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Fabri
 */
import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Gato; 
import modelo.Hogar_Adopcion;
import modelo.Usuario;
import modelo.Veterinario; 
import modelo.Visita;
import modelo.Voluntario;
import servicio.Swingcontexto;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.GridLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JScrollPane; 
import javax.swing.JTextArea; 
import java.awt.Dimension;

public class Panelvisitas extends javax.swing.JPanel {
    private Swingcontexto servicios;
    private Usuario usuarioLogueado;
    private DefaultTableModel modeloTabla;
    private static final DateTimeFormatter FORMATO_FECHA = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
    /**
     * Creates new form Panelvisitas
     */
    public Panelvisitas(Swingcontexto servicios, Usuario usuarioLogueado) {
        this.servicios = servicios;
        this.usuarioLogueado = usuarioLogueado;
        initComponents();
        configurarTabla();
        cargarDatosTabla(servicios.gestionVisitas.listarVisitas());
        if (usuarioLogueado.getRol() != 1) {
            EVALUAR_VISITAS.setVisible(false);
        }
    }
    private void configurarTabla() {
        modeloTabla = new DefaultTableModel() {
            @Override public boolean isCellEditable(int row, int column) { return false; }
        };
        
        modeloTabla.addColumn("ID Visita");
        modeloTabla.addColumn("Fecha Programada");
        modeloTabla.addColumn("VoluntARIO");
        modeloTabla.addColumn("Hogar (Familia)");
        modeloTabla.addColumn("Observacion");
        modeloTabla.addColumn("Estado"); 
        
        tablaVisitas.setModel(modeloTabla); 
    }
    private void cargarDatosTabla(List<Visita> visitas) {
        modeloTabla.setRowCount(0); 
        for (Visita v : visitas) {
            Object[] fila = {
                v.getCodvisita(),(v.getFechahora() != null) ? v.getFechahora().format(FORMATO_FECHA) : "N/A",
                (v.getVoluntario() != null) ? v.getVoluntario().getNombre() : "N/A",(v.getAdopcion() != null && v.getAdopcion().getFamilia() != null) ? v.getAdopcion().getFamilia().getNombre() + " (Hogar ID: " + v.getAdopcion().getIdhogarfam() + ")" : "N/A",v.getObservacion(), v.isCumplida() ? "Cumplida" : "Pendiente"};
            modeloTabla.addRow(fila);
        }
    }
    private Visita obtenerVisitaDeTabla() throws Exception {
         int filaSel = tablaVisitas.getSelectedRow();
         if (filaSel == -1) {
             throw new Exception("Debe seleccionar una visita de la tabla.");
         }
         int idVisita = (int) modeloTabla.getValueAt(filaSel, 0); 
         Visita visita = servicios.gestionVisitas.buscarVisitaPorId(idVisita);
         if (visita == null) {
             cargarDatosTabla(servicios.gestionVisitas.listarVisitas()); 
             throw new Exception("La visita seleccionada ya no existe. La tabla ha sido actualizada.");
         }
         return visita;
    }
    private JComboBox<Voluntario> crearComboVoluntarios() {
        JComboBox<Voluntario> cmbVol = new JComboBox<>();
        List<Usuario> usuarios = servicios.usuarioService.listarUsuarios();
        DefaultComboBoxModel<Voluntario> comboModel = new DefaultComboBoxModel<>();
        comboModel.addElement(null); 
        for (Usuario u : usuarios) {
            if (u instanceof Voluntario) {
                comboModel.addElement((Voluntario) u);
            }
        }
        cmbVol.setModel(comboModel);
        cmbVol.setRenderer(new VoluntarioComboBoxRenderer()); 
        return cmbVol;
    }
    private JComboBox<Hogar_Adopcion> crearComboHogares() {
        JComboBox<Hogar_Adopcion> cmbHogar = new JComboBox<>();
        List<Hogar_Adopcion> hogares = servicios.gestionVisitas.listarHogares();
        DefaultComboBoxModel<Hogar_Adopcion> comboModel = new DefaultComboBoxModel<>();
        comboModel.addElement(null); 
        for (Hogar_Adopcion h : hogares) {
            comboModel.addElement(h);
        }
        cmbHogar.setModel(comboModel);
        cmbHogar.setRenderer(new HogarComboBoxRenderer()); 
        return cmbHogar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scroll = new javax.swing.JScrollPane();
        tablaVisitas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        AÑADIR = new javax.swing.JButton();
        MODIFICAR = new javax.swing.JButton();
        ELIMINAR = new javax.swing.JButton();
        EVALUAR_VISITAS = new javax.swing.JButton();
        VER_ALERTAS = new javax.swing.JButton();
        ACTUALIZAR_LISTA = new javax.swing.JButton();
        IDvisita = new javax.swing.JTextField();
        BUSCAR = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GESTOR VISITAS", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N
        setLayout(new java.awt.BorderLayout());

        tablaVisitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scroll.setViewportView(tablaVisitas);

        add(scroll, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("ID VISITA");

        AÑADIR.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        AÑADIR.setText("AÑADIR");
        AÑADIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AÑADIRActionPerformed(evt);
            }
        });

        MODIFICAR.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        MODIFICAR.setText("MODIFICAR");
        MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFICARActionPerformed(evt);
            }
        });

        ELIMINAR.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ELIMINAR.setText("ELIMINAR");
        ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ELIMINARActionPerformed(evt);
            }
        });

        EVALUAR_VISITAS.setText("EVALUAR VISITAS");
        EVALUAR_VISITAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EVALUAR_VISITASActionPerformed(evt);
            }
        });

        VER_ALERTAS.setText("MIS ALERTAS");
        VER_ALERTAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VER_ALERTASActionPerformed(evt);
            }
        });

        ACTUALIZAR_LISTA.setText("ACTUALIZAR LISTA");
        ACTUALIZAR_LISTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACTUALIZAR_LISTAActionPerformed(evt);
            }
        });

        IDvisita.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        BUSCAR.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BUSCAR.setText("BUSCAR");
        BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AÑADIR, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MODIFICAR, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                        .addComponent(EVALUAR_VISITAS)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(VER_ALERTAS))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDvisita, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ACTUALIZAR_LISTA))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(IDvisita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUSCAR))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MODIFICAR)
                            .addComponent(ELIMINAR))
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(AÑADIR)
                        .addContainerGap(22, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ACTUALIZAR_LISTA, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VER_ALERTAS, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EVALUAR_VISITAS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void EVALUAR_VISITASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EVALUAR_VISITASActionPerformed
        if (usuarioLogueado.getRol() != 1) {
            JOptionPane.showMessageDialog(this, "Esta accion solo esta permitida para Administradores.", "Accion Denegada", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            Visita visita = obtenerVisitaDeTabla();
            String[] opciones = {"Marcar como Cumplida", "Marcar como No Cumplida"};
            int seleccion = JOptionPane.showOptionDialog(this, "Como deseas evaluar la Visita #" + visita.getCodvisita() + "?", "Evaluar Visita", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones,opciones[0]);
            boolean fueCumplida = (seleccion == 0); // 0 = Cumplida, 1 = No Cumplida
            servicios.gestionVisitas.evaluarVisita(visita, fueCumplida);
            JOptionPane.showMessageDialog(this, "Visita evaluada. Reputaciones actualizadas.", "exito", JOptionPane.INFORMATION_MESSAGE);
            cargarDatosTabla(servicios.gestionVisitas.listarVisitas()); 
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al evaluar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_EVALUAR_VISITASActionPerformed

    private void VER_ALERTASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VER_ALERTASActionPerformed
        List<String> alertas;
        String tituloPopUp;
        if (usuarioLogueado.getRol() == 1) { 
            tituloPopUp = "Todas las Alertas de Visitas (Admin)";
            alertas = servicios.gestionVisitas.mostrarAlertasVisitas(); 
            
        }   else if (usuarioLogueado.getRol() == 3) { 
                tituloPopUp = "Mis Alertas de Visitas (" + usuarioLogueado.getNombre() + ")";
                alertas = servicios.gestionVisitas.mostrarAlertasVisitas((Voluntario) usuarioLogueado);
            
            } else {
                    JOptionPane.showMessageDialog(this, "No tienes permisos para esta accion.", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                    if (alertas.isEmpty()) {
                        JOptionPane.showMessageDialog(this, "No hay alertas de visitas activas.", tituloPopUp, JOptionPane.INFORMATION_MESSAGE);
                        return;
                    }
                    StringBuilder reporte = new StringBuilder(tituloPopUp + "\n\n");
                    for (String alerta : alertas) {
                        reporte.append(alerta).append("\n\n");
                    }
                    JTextArea textArea = new JTextArea(reporte.toString());
                    textArea.setEditable(false);
                    JScrollPane scrollPane = new JScrollPane(textArea);
                    scrollPane.setPreferredSize(new Dimension(500, 400));
                    JOptionPane.showMessageDialog(this, scrollPane, tituloPopUp, JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_VER_ALERTASActionPerformed

    private void ACTUALIZAR_LISTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACTUALIZAR_LISTAActionPerformed
        cargarDatosTabla(servicios.gestionVisitas.listarVisitas());
        IDvisita.setText(""); 
    }//GEN-LAST:event_ACTUALIZAR_LISTAActionPerformed

    private void ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ELIMINARActionPerformed
        try {
            Visita visita = obtenerVisitaDeTabla();
            
            if (usuarioLogueado.getRol() == 3) { 
                if (visita.getVoluntario() == null || !visita.getVoluntario().getDNI().equals(usuarioLogueado.getDNI())) {
                    throw new Exception("Como voluntario, solo puedes eliminar tus propias visitas.");
                }
            }
            int confirm = JOptionPane.showConfirmDialog(this,"Seguro que deseas eliminar la Visita #" + visita.getCodvisita() + "?","Confirmar Eliminacion", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                
            if (confirm == JOptionPane.YES_OPTION) {
                servicios.gestionVisitas.borrarVisita(visita);
                JOptionPane.showMessageDialog(this, "Visita eliminada.", "exito", JOptionPane.INFORMATION_MESSAGE);
                cargarDatosTabla(servicios.gestionVisitas.listarVisitas()); 
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ELIMINARActionPerformed

    private void MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFICARActionPerformed
        try {
             Visita visita = obtenerVisitaDeTabla();
             try{
                    if (usuarioLogueado.getRol() == 3) { 
                        if (visita.getVoluntario() == null) {
                            throw new Exception("No puedes modificar una visita que no tiene voluntario asignado.");
                        }
                        if (!visita.getVoluntario().getDNI().equals(usuarioLogueado.getDNI())) {
                            throw new Exception("Como voluntario, solo puedes modificar tus propias visitas.");
                        }
                    }
              
            JComboBox<Voluntario> cmbVol = crearComboVoluntarios();
            cmbVol.setSelectedItem(visita.getVoluntario());
            
            JComboBox<Hogar_Adopcion> cmbHogar = crearComboHogares();
            cmbHogar.setSelectedItem(visita.getAdopcion());
            
            JTextField txtFecha = new JTextField(visita.getFechahora().format(FORMATO_FECHA));
            JTextField txtObservacion = new JTextField(visita.getObservacion());

            JPanel dialogPanel = new JPanel(new GridLayout(4, 2, 5, 5));
            dialogPanel.add(new JLabel("Voluntario:"));
            dialogPanel.add(cmbVol);
            dialogPanel.add(new JLabel("Hogar:"));
            dialogPanel.add(cmbHogar);
            dialogPanel.add(new JLabel("Fecha Programada:"));
            dialogPanel.add(txtFecha);
            dialogPanel.add(new JLabel("Observacion:"));
            dialogPanel.add(txtObservacion);

            int result = JOptionPane.showConfirmDialog(this, dialogPanel, "Modificar Visita #" + visita.getCodvisita(),
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

            if (result == JOptionPane.OK_OPTION) {
                Voluntario volSel = (Voluntario) cmbVol.getSelectedItem();
                Hogar_Adopcion hogarSel = (Hogar_Adopcion) cmbHogar.getSelectedItem();
                String fechaStr = txtFecha.getText();
                String obs = txtObservacion.getText();
                servicios.gestionVisitas.modificarVisita(visita, volSel, hogarSel, fechaStr, obs);
                
                JOptionPane.showMessageDialog(this, "Visita actualizada.", "exito", JOptionPane.INFORMATION_MESSAGE);
                cargarDatosTabla(servicios.gestionVisitas.listarVisitas()); 
            }
             }
             catch(Exception e){
                 JOptionPane.showMessageDialog(this, "Error al modificar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
             }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al modificar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_MODIFICARActionPerformed

    private void AÑADIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AÑADIRActionPerformed

        JComboBox<Voluntario> cmbVol = crearComboVoluntarios();
        JComboBox<Hogar_Adopcion> cmbHogar = crearComboHogares();
        JTextField txtFecha = new JTextField(LocalDateTime.now().plusDays(1).format(FORMATO_FECHA)); 
        JTextField txtObservacion = new JTextField();
        JPanel dialogPanel = new JPanel(new GridLayout(4, 2, 5, 5));
        dialogPanel.add(new JLabel("Voluntario:"));
        dialogPanel.add(cmbVol);
        dialogPanel.add(new JLabel("Hogar:"));
        dialogPanel.add(cmbHogar);
        dialogPanel.add(new JLabel("Fecha Programada (dd/MM/yyyy HH:mm):"));
        dialogPanel.add(txtFecha);
        dialogPanel.add(new JLabel("Observacion:"));
        dialogPanel.add(txtObservacion);
        int result = JOptionPane.showConfirmDialog(this, dialogPanel, "Registrar Nueva Visita",JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            try {
                Voluntario volSel = (Voluntario) cmbVol.getSelectedItem();
                Hogar_Adopcion hogarSel = (Hogar_Adopcion) cmbHogar.getSelectedItem();
                String fechaStr = txtFecha.getText();
                String obs = txtObservacion.getText();
                servicios.gestionVisitas.registrarVisita(volSel, hogarSel, fechaStr, obs);
                
                JOptionPane.showMessageDialog(this, "Visita registrada con exito.", "exito", JOptionPane.INFORMATION_MESSAGE);
                cargarDatosTabla(servicios.gestionVisitas.listarVisitas()); 

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al registrar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_AÑADIRActionPerformed

    private void BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSCARActionPerformed
        try {
            String idStr = IDvisita.getText().trim();
            
            if (idStr.isEmpty()) {
                throw new Exception("Por favor, ingrese un ID de Visita para buscar.");
            }
            int idVisita = Integer.parseInt(idStr);
            Visita visita = servicios.gestionVisitas.buscarVisitaPorId(idVisita);
            if (visita != null) {
                List<Visita> listaBusqueda = new ArrayList<>();
                listaBusqueda.add(visita);
                cargarDatosTabla(listaBusqueda); 
            } else {
                JOptionPane.showMessageDialog(this, "No se encontro ninguna visita con el ID: " + idVisita, "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ingrese un ID  valido.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error al Buscar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BUSCARActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACTUALIZAR_LISTA;
    private javax.swing.JButton AÑADIR;
    private javax.swing.JButton BUSCAR;
    private javax.swing.JButton ELIMINAR;
    private javax.swing.JButton EVALUAR_VISITAS;
    private javax.swing.JTextField IDvisita;
    private javax.swing.JButton MODIFICAR;
    private javax.swing.JButton VER_ALERTAS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane scroll;
    private javax.swing.JTable tablaVisitas;
    // End of variables declaration//GEN-END:variables
}
class HogarComboBoxRenderer extends javax.swing.plaf.basic.BasicComboBoxRenderer {
    @Override
    public java.awt.Component getListCellRendererComponent(
            javax.swing.JList list, Object value, int index,
            boolean isSelected, boolean cellHasFocus) {
        
        super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);

        if (value instanceof Hogar_Adopcion) {
            Hogar_Adopcion hogar = (Hogar_Adopcion) value;
            String nombreFamilia = (hogar.getFamilia() != null) ? hogar.getFamilia().getNombre() : "Familia Desconocida";
            setText(nombreFamilia + " (ID Hogar: " + hogar.getIdhogarfam() + ")");
        } else if (value == null) {
            setText("Seleccione un hogar...");
        }
        return this;
    }
}
