/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Fabri
 */
import java.util.List;
import java.util.ArrayList; 
import javax.swing.table.DefaultTableModel;
import modelo.Diagnosticos;
import modelo.Gato;
import modelo.Usuario;
import modelo.Veterinario;
import servicio.Swingcontexto; 
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JCheckBox;
import java.awt.GridLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTextArea;
import javax.swing.JScrollPane;
import java.awt.Dimension;

public class PanelDiagnosticos extends javax.swing.JPanel {
    private Swingcontexto servicios;
    private Usuario usuarioLogueado; 
    private DefaultTableModel modeloTabla;
    private static final DateTimeFormatter FORMATO_FECHA = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
    /**
     * Creates new form PanelDiagnosticos
     */
    
    public PanelDiagnosticos(Swingcontexto servicios, Usuario usuarioLogueado) {
       this.servicios = servicios;
        this.usuarioLogueado = usuarioLogueado;
        initComponents();
        configurarTabla();
        cargarDatosTabla(servicios.diagnosticoService.mostrarDiagnosticos());
    }
    private void configurarTabla() {
        modeloTabla = new DefaultTableModel() {
            @Override public boolean isCellEditable(int row, int column) { return false; }
        };
        
        modeloTabla.addColumn("ID Diag.");
        modeloTabla.addColumn("Fecha Límite");
        modeloTabla.addColumn("Paciente (Gato)");
        modeloTabla.addColumn("Veterinario");
        modeloTabla.addColumn("Diagnóstico");
        modeloTabla.addColumn("Tratamiento");
        modeloTabla.addColumn("Estado"); 
        
        jTable1.setModel(modeloTabla); 
    }
    
    private void cargarDatosTabla(List<Diagnosticos> diagnosticos) {
        modeloTabla.setRowCount(0); 
        
        for (Diagnosticos d : diagnosticos) {
            Object[] fila = {
                d.getId_diagnostico(),
                (d.getFecha() != null) ? d.getFecha().format(FORMATO_FECHA) : "N/A",
                (d.getPaciente() != null) ? d.getPaciente().getNombre() : "N/A",
                (d.getAutor() != null) ? d.getAutor().getNombre() : "N/A",
                d.getDiagnostico(),
                d.getTratamiento(),
                d.isEstado() ? "Completado" : "Pendiente"
            };
            modeloTabla.addRow(fila);
        }
    }
    private JComboBox<Gato> crearComboGatos() {
        JComboBox<Gato> cmbGatos = new JComboBox<>();
        List<Gato> gatos = servicios.gatoService.listarGatos();
        DefaultComboBoxModel<Gato> comboModel = new DefaultComboBoxModel<>();
        comboModel.addElement(null); 
        for (Gato g : gatos) {
            comboModel.addElement(g);
        }
        cmbGatos.setModel(comboModel);
        return cmbGatos;
    }
    private Gato obtenerGatodeTabla() throws Exception {
        Diagnosticos diag = obtenerDiagnosticoDeTabla(); 
        
        if (diag.getPaciente() == null) {
            throw new Exception("El diagnostico seleccionado (ID: " + diag.getId_diagnostico() + ") no tiene un gato (paciente) asociado.");
        }
        return diag.getPaciente();
    }
    private Diagnosticos obtenerDiagnosticoDeTabla() throws Exception {
         int filaSel = jTable1.getSelectedRow();
         if (filaSel == -1) {
             throw new Exception("Debe seleccionar un diagnostico de la tabla");
         }
         
         int idDiag = (int) modeloTabla.getValueAt(filaSel, 0); 
         
         Diagnosticos diag = servicios.diagnosticoService.buscarporID(idDiag); 
         
         if (diag == null) {
             cargarDatosTabla(servicios.diagnosticoService.mostrarDiagnosticos());
             throw new Exception("El diagnostico seleccionado ya no existe. La tabla ha sido actualizada");
         }
         return diag;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        BUSCAR = new javax.swing.JButton();
        AÑADIR = new javax.swing.JButton();
        ELIMINAR = new javax.swing.JButton();
        ESTERILIZADO = new javax.swing.JButton();
        HISTORIALCLINICO = new javax.swing.JButton();
        APTO = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        MODIFICAR = new javax.swing.JButton();
        ACTUALIZARLISTA = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GESTOR DIAGNOSTICOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        BUSCAR.setText("BUSCAR");
        BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCARActionPerformed(evt);
            }
        });

        AÑADIR.setText("AÑADIR");
        AÑADIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AÑADIRActionPerformed(evt);
            }
        });

        ELIMINAR.setText("ELIMINAR");
        ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ELIMINARActionPerformed(evt);
            }
        });

        ESTERILIZADO.setText("ESTERILIZACION");
        ESTERILIZADO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ESTERILIZADOActionPerformed(evt);
            }
        });

        HISTORIALCLINICO.setText("VER HISTORIAL");
        HISTORIALCLINICO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HISTORIALCLINICOActionPerformed(evt);
            }
        });

        APTO.setText("MARCAR APTO");
        APTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                APTOActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("INGRESE ID");

        jTextField1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        MODIFICAR.setText("MODIFICAR");
        MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFICARActionPerformed(evt);
            }
        });

        ACTUALIZARLISTA.setText("ACT LISTA");
        ACTUALIZARLISTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACTUALIZARLISTAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(AÑADIR, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MODIFICAR, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HISTORIALCLINICO, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ESTERILIZADO, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(APTO, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(ACTUALIZARLISTA)
                .addGap(88, 88, 88))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUSCAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ESTERILIZADO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(HISTORIALCLINICO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ELIMINAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AÑADIR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(APTO, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(MODIFICAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(ACTUALIZARLISTA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSCARActionPerformed
        try {
            String idStr = jTextField1.getText().trim();
            if (idStr.isEmpty()) {
                cargarDatosTabla(servicios.diagnosticoService.mostrarDiagnosticos());
                JOptionPane.showMessageDialog(this, "Mostrando todos los diagnosticos.", "Busqueda", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            int idDiag = Integer.parseInt(idStr);
            Diagnosticos diag = servicios.diagnosticoService.buscarporID(idDiag);
            
            if (diag != null) {
                List<Diagnosticos> listaBusqueda = new ArrayList<>();
                listaBusqueda.add(diag);
                cargarDatosTabla(listaBusqueda); 
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró ningun diagnóstico con el ID: " + idDiag, "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ingrese un ID valido para el diagnostico.", "Error de Formato", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error al Buscar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BUSCARActionPerformed

    private void AÑADIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AÑADIRActionPerformed

        JTextField txtFecha = new JTextField(LocalDateTime.now().format(FORMATO_FECHA));
        JComboBox<Gato> cmbGatos = crearComboGatos();
        JTextField txtDiagnostico = new JTextField();
        JTextField txtTratamiento = new JTextField();
        JTextField txtDescripcion = new JTextField();
        JPanel dialogPanel = new JPanel(new GridLayout(5, 2, 5, 5));
        dialogPanel.add(new JLabel("Fecha Limite (dd/MM/yyyy HH:mm):"));
        dialogPanel.add(txtFecha);
        dialogPanel.add(new JLabel("Paciente (Gato):"));
        dialogPanel.add(cmbGatos);
        dialogPanel.add(new JLabel("Diagnostico:"));
        dialogPanel.add(txtDiagnostico);
        dialogPanel.add(new JLabel("Tratamiento:"));
        dialogPanel.add(txtTratamiento);
        dialogPanel.add(new JLabel("Descripcion del diagnostico:"));
        dialogPanel.add(txtDescripcion);

        int result = JOptionPane.showConfirmDialog(
                this, dialogPanel, "Crear Nuevo Diagnostico",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE
        );
        if (result == JOptionPane.OK_OPTION) {
            try {
                Gato gatoSel = (Gato) cmbGatos.getSelectedItem();
                Veterinario vet = (Veterinario) usuarioLogueado;
                String fechaStr = txtFecha.getText();
                String diag = txtDiagnostico.getText();
                String trat = txtTratamiento.getText();
                String desc = txtDescripcion.getText();
                servicios.diagnosticoService.crearDiagnostico(gatoSel, vet, fechaStr, diag, trat, desc);
                
                JOptionPane.showMessageDialog(this, "Diagnostico creado con exito.", "exito", JOptionPane.INFORMATION_MESSAGE);
                cargarDatosTabla(servicios.diagnosticoService.mostrarDiagnosticos()); 
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al crear: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_AÑADIRActionPerformed

    private void ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ELIMINARActionPerformed
        try {
            Diagnosticos diag = obtenerDiagnosticoDeTabla();
            int confirm = JOptionPane.showConfirmDialog(this, "Seguro que deseas eliminar el Diagnostico #" + diag.getId_diagnostico() + "?","Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (confirm == JOptionPane.YES_OPTION) {
                servicios.diagnosticoService.eliminarDiagnostico(diag);
                JOptionPane.showMessageDialog(this, "Diagnostico eliminado.", "exito", JOptionPane.INFORMATION_MESSAGE);
                cargarDatosTabla(servicios.diagnosticoService.mostrarDiagnosticos()); 
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ELIMINARActionPerformed

    private void ESTERILIZADOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ESTERILIZADOActionPerformed
        try {
            Gato gato = obtenerGatodeTabla();
            
            int confirm = JOptionPane.showConfirmDialog(this, "Marcar a '" + gato.getNombre() + "' como esterilizado?","Confirmar", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                gato.esterilizado(); 
                servicios.gatoService.marcarEsterilizado(gato);
                JOptionPane.showMessageDialog(this, "Gato marcado como esterilizado", "exito", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ESTERILIZADOActionPerformed

    private void HISTORIALCLINICOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HISTORIALCLINICOActionPerformed
        try {
            Gato gato = obtenerGatodeTabla(); 
            List<Diagnosticos> historial = servicios.diagnosticoService.mostrarHistorialPorGato(gato);
            if (historial.isEmpty()) {
                JOptionPane.showMessageDialog(this,"El gato '" + gato.getNombre() + "' no tiene diagnosticos registrados.", "Historial Clinico", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
            StringBuilder reporte = new StringBuilder();
            reporte.append("--- Historial Clinico de: " + gato.getNombre() + " (ID: " + gato.getId() + ") ---\n\n");
            for (Diagnosticos d : historial) {
                reporte.append(d.toString()); 
                reporte.append("\n----------------------------------\n");
            }
            JTextArea textArea = new JTextArea(reporte.toString());
            textArea.setEditable(false);
            textArea.setLineWrap(true);
            textArea.setWrapStyleWord(true);
            JScrollPane scrollPane = new JScrollPane(textArea);
            scrollPane.setPreferredSize(new Dimension(500, 400)); 
            JOptionPane.showMessageDialog(this, scrollPane, "Historial Clinico de " + gato.getNombre(), JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error al Cargar Historial", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_HISTORIALCLINICOActionPerformed

    private void APTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_APTOActionPerformed
        try {
            Gato gato = obtenerGatodeTabla();
            
            int confirm = JOptionPane.showConfirmDialog(this, "Marcar a '" + gato.getNombre() + "' como APTO para adopción?\n(Se verificaran sus diagnósticos)","Marcar apto", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                servicios.diagnosticoService.marcarApto(gato); 
                JOptionPane.showMessageDialog(this, "Gato '" + gato.getNombre() + "' marcado como APTO.", "exito", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error al Marcar apto", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_APTOActionPerformed

    private void MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFICARActionPerformed
        try {
            Diagnosticos diag = obtenerDiagnosticoDeTabla(); 
            JTextField txtTratamiento = new JTextField(diag.getTratamiento());
            JTextField txtDescripcion = new JTextField(diag.getDescripcion());
            JCheckBox chkCompletado = new JCheckBox("Marcar como Completado", diag.isEstado());
            JPanel dialogPanel = new JPanel(new GridLayout(3, 2, 5, 5));
            dialogPanel.add(new JLabel("Tratamiento:"));
            dialogPanel.add(txtTratamiento);
            dialogPanel.add(new JLabel("Descripcion:"));
            dialogPanel.add(txtDescripcion);
            dialogPanel.add(new JLabel("Estado:"));
            dialogPanel.add(chkCompletado);
            int result = JOptionPane.showConfirmDialog(this, dialogPanel, "Actualizar Diagnostico #" + diag.getId_diagnostico(),JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (result == JOptionPane.OK_OPTION) {
                String nuevoTrat = txtTratamiento.getText();
                String nuevaDesc = txtDescripcion.getText();
                boolean completado = chkCompletado.isSelected();
                servicios.diagnosticoService.actualizarDiagnostico(diag, nuevoTrat, nuevaDesc, completado);
                JOptionPane.showMessageDialog(this, "Diagnostico actualizado.", "exito", JOptionPane.INFORMATION_MESSAGE);
                cargarDatosTabla(servicios.diagnosticoService.mostrarDiagnosticos()); 
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al actualizar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_MODIFICARActionPerformed

    private void ACTUALIZARLISTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACTUALIZARLISTAActionPerformed

        List<Diagnosticos> todos = servicios.diagnosticoService.mostrarDiagnosticos();
        cargarDatosTabla(todos);
        jTextField1.setText("");
    }//GEN-LAST:event_ACTUALIZARLISTAActionPerformed
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACTUALIZARLISTA;
    private javax.swing.JButton APTO;
    private javax.swing.JButton AÑADIR;
    private javax.swing.JButton BUSCAR;
    private javax.swing.JButton ELIMINAR;
    private javax.swing.JButton ESTERILIZADO;
    private javax.swing.JButton HISTORIALCLINICO;
    private javax.swing.JButton MODIFICAR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
