/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Fabri
 */
import java.awt.Color; 
import java.awt.Component;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import modelo.Diagnosticos;
import modelo.EventoCalendario;
import modelo.Tarea;
import modelo.Usuario;
import modelo.Visita;
import servicio.Swingcontexto;
import javax.swing.JOptionPane;

public class PanelCalendario extends javax.swing.JPanel {
    private Swingcontexto servicios;
    private Usuario usuarioLogueado;
    private DefaultTableModel modeloTabla;
    private static final DateTimeFormatter FORMATO_FECHA = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
    /**
     * Creates new form PanelCalendario
     */
    public PanelCalendario(Swingcontexto servicios, Usuario usuarioLogueado) {
        this.servicios = servicios;
        this.usuarioLogueado = usuarioLogueado;
        initComponents();
        configurarTabla();
        Proximos7DiasActionActionPerformed(null);
        if (usuarioLogueado.getRol() != 1) {
           AsignarAuto.setVisible(false);
        }
    }
    private void configurarTabla() {
        modeloTabla = new DefaultTableModel() {
            @Override public boolean isCellEditable(int row, int column) { return false; }
        };
        
        modeloTabla.addColumn("Fecha Limite");
        modeloTabla.addColumn("Tipo de Evento");
        modeloTabla.addColumn("Encargado");
        modeloTabla.addColumn("Descripcion"); 
        modeloTabla.addColumn("Estado");
        
        tablaCalendario.setModel(modeloTabla);
        tablaCalendario.getColumnModel().getColumn(4).setCellRenderer(new EstadoCalendarioRenderer());
    }
    private void cargarDatosTabla(List<EventoCalendario> eventos) {
        modeloTabla.setRowCount(0); 
        
        for (EventoCalendario evento : eventos) {
            String tipoEvento = evento.getClass().getSimpleName();
            String estado = "Desconocido";
            String encargado = "N/A"; 
            if (evento.estaVencido()) {
                estado = "VENCIDO";
            } else if (evento.requiereAlerta()) {
                estado = "Próximo a Vencer";
            } else {
                estado = "Pendiente";
            }
            if (evento instanceof Tarea tarea) {
                estado = switch (tarea.getEstado()) {
                    case 0 -> estado; 
                    case 1 -> "Completado";
                    case 2 -> "Incompleta";
                    default -> "N/A";
                };
                encargado = (tarea.getVoluntario() != null) ? tarea.getVoluntario().getNombre() : "SIN ASIGNAR";
            } else if (evento instanceof Diagnosticos diag) {
                if (diag.isEstado()) estado = "Completado";
                encargado = (diag.getAutor() != null) ? diag.getAutor().getNombre() : "N/A";
            } else if (evento instanceof Visita visita) {
                if (visita.isCumplida()) estado = "Completado";
                encargado = (visita.getVoluntario() != null) ? visita.getVoluntario().getNombre() : "N/A";
            }
            Object[] fila = {(evento.getFecha() != null) ? evento.getFecha().format(FORMATO_FECHA):"N/A",tipoEvento,evento.getDescripcion(),encargado, estado};
            modeloTabla.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaCalendario = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        VER_TODOS = new javax.swing.JButton();
        Proximos7DiasAction = new javax.swing.JButton();
        ALERTAS = new javax.swing.JButton();
        AsignarAuto = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CALENDARIO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 24))); // NOI18N
        setLayout(new java.awt.BorderLayout());

        tablaCalendario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaCalendario);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        VER_TODOS.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        VER_TODOS.setText("VER TODOS");
        VER_TODOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VER_TODOSActionPerformed(evt);
            }
        });

        Proximos7DiasAction.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Proximos7DiasAction.setText("PROX. 7 DIAS");
        Proximos7DiasAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Proximos7DiasActionActionPerformed(evt);
            }
        });

        ALERTAS.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ALERTAS.setText("MOSTRAR ALERTAS");
        ALERTAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ALERTASActionPerformed(evt);
            }
        });

        AsignarAuto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        AsignarAuto.setText("ASIGNAR AUTO");
        AsignarAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsignarAutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(VER_TODOS, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ALERTAS, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Proximos7DiasAction, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AsignarAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VER_TODOS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Proximos7DiasAction)
                    .addComponent(ALERTAS)
                    .addComponent(AsignarAuto))
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void VER_TODOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VER_TODOSActionPerformed
        cargarDatosTabla(servicios.calendarioService.obtenerTodosLosEventosOrdenados());
    }//GEN-LAST:event_VER_TODOSActionPerformed

    private void ALERTASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ALERTASActionPerformed
       cargarDatosTabla(servicios.calendarioService.listarAlertas());
    }//GEN-LAST:event_ALERTASActionPerformed

    private void Proximos7DiasActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Proximos7DiasActionActionPerformed
        cargarDatosTabla(servicios.calendarioService.listarEventosProximos(7));
    }//GEN-LAST:event_Proximos7DiasActionActionPerformed

    private void AsignarAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsignarAutoActionPerformed
       try{
        String resultado = servicios.tareaService.asignarTareasPendientes(); 
            if (resultado.startsWith("Error") || resultado.startsWith("Advertencia")) {
                JOptionPane.showMessageDialog(this,resultado,"Asignacion Automatica", JOptionPane.WARNING_MESSAGE); 
            } else {
                 JOptionPane.showMessageDialog(this,resultado, "Asignacion Exitosa", JOptionPane.INFORMATION_MESSAGE); 
            }
            cargarDatosTabla(servicios.calendarioService.obtenerTodosLosEventosOrdenados());
        } catch (Exception e) { 
            JOptionPane.showMessageDialog(this, 
                "Error critico durante la asignacion: " + e.getMessage(),"Error Critico", JOptionPane.ERROR_MESSAGE);
        }
    

    }//GEN-LAST:event_AsignarAutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ALERTAS;
    private javax.swing.JButton AsignarAuto;
    private javax.swing.JButton Proximos7DiasAction;
    private javax.swing.JButton VER_TODOS;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaCalendario;
    // End of variables declaration//GEN-END:variables
}
class EstadoCalendarioRenderer extends DefaultTableCellRenderer {
    
    private final Color COLOR_VENCIDO = new Color(255, 100, 100); 
    private final Color COLOR_ALERTA = new Color(255, 210, 100); 
    private final Color COLOR_COMPLETADO = new Color(100, 200, 100); 
    private final Color COLOR_PENDIENTE = Color.WHITE; 
    @Override
    public Component getTableCellRendererComponent(JTable table, Object value,boolean isSelected, boolean hasFocus,int row, int column) {
        Component c = super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column);
        String estado = (value != null) ? value.toString() : "";
        
        if (!isSelected) {
            if (estado.equals("VENCIDO")) {
                c.setBackground(COLOR_VENCIDO);
                c.setForeground(Color.BLACK);
            } else if (estado.equals("Proximo a Vencer")) {
                c.setBackground(COLOR_ALERTA);
                c.setForeground(Color.BLACK);
            } else if (estado.equals("Completado")) {
                c.setBackground(COLOR_COMPLETADO);
                c.setForeground(Color.BLACK);
            } else { 
                c.setBackground(COLOR_PENDIENTE);
                c.setForeground(table.getForeground());
            }
        } else {
             c.setBackground(table.getSelectionBackground());
             c.setForeground(table.getSelectionForeground());
        }

        return c;
    }
}