/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Fabri
 */
import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Gato;
import modelo.Hogar_Adopcion;
import modelo.Usuario;
import modelo.Familia;
import servicio.Swingcontexto;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import java.awt.GridLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import java.awt.Dimension;


public class PanelHogares extends javax.swing.JPanel {
    private Swingcontexto servicios;
    private Usuario usuarioLogueado;
    private DefaultTableModel modeloTabla;
    /**
     * Creates new form PanelHogares
     */
    public PanelHogares(Swingcontexto servicios, Usuario usuarioLogueado) {
        this.servicios = servicios;
        this.usuarioLogueado = usuarioLogueado;
        initComponents();
        configurarTabla();
        cargarDatosTabla(servicios.gestionHogares.listarHogares());
    }
    private void configurarTabla() {
        modeloTabla = new DefaultTableModel() {
            @Override public boolean isCellEditable(int row, int column) { return false; }
        };
        modeloTabla.addColumn("ID Hogar");
        modeloTabla.addColumn("Direccion");
        modeloTabla.addColumn("Coordenadas");
        modeloTabla.addColumn("Familia)");
        modeloTabla.addColumn("Gatos Asig.");
        modeloTabla.addColumn("Postulado");
        modeloTabla.addColumn("Aprobado");
        tablaHogares.setModel(modeloTabla); 
    }
    private void cargarDatosTabla(List<Hogar_Adopcion> hogares) {
        modeloTabla.setRowCount(0); 
        for (Hogar_Adopcion h : hogares) {
            String familiaNombre = (h.getFamilia() != null) ? h.getFamilia().getNombre() : "N/A";
            boolean postulado = (h.getFamilia() != null) ? h.getFamilia().isPostulado() : false;
            Object[] fila = {h.getIdhogarfam(),h.getDireccion(),h.getCoordenadas(),familiaNombre + " (DNI: " + (h.getFamilia() != null ? h.getFamilia().getDNI() : "N/A") + ")",(h.getGatos() != null) ? h.getGatos().size() : 0,postulado ? "Sí" : "No",h.isAprobado() ? "APROBADO" : "Pendiente"};
            modeloTabla.addRow(fila);
        }
    }
    private Hogar_Adopcion obtenerHogarDeTabla() throws Exception {
         int filaSel = tablaHogares.getSelectedRow();
         if (filaSel == -1) {
             throw new Exception("Debe seleccionar un hogar de la tabla.");
         }
         int idHogar = (int) modeloTabla.getValueAt(filaSel, 0); 
         Hogar_Adopcion hogar = servicios.gestionHogares.buscarHogarPorId(idHogar);
         if (hogar == null) {
             cargarDatosTabla(servicios.gestionHogares.listarHogares()); 
             throw new Exception("El hogar seleccionado ya no existe. La tabla ha sido actualizada.");
         }
         return hogar;
    }
    private JComboBox<Familia> crearComboFamiliasSinHogar() {
        JComboBox<Familia> cmbFamilias = new JComboBox<>();
        List<Usuario> usuarios = servicios.usuarioService.listarUsuarios();
        DefaultComboBoxModel<Familia> comboModel = new DefaultComboBoxModel<>();
        comboModel.addElement(null); 
        for (Usuario u : usuarios) {
            if (u instanceof Familia) {
                Familia f = (Familia) u;
                if (servicios.gestionHogares.buscarHogarPorFamilia(f) == null) {
                    comboModel.addElement(f);
                }
            }
        }
        cmbFamilias.setModel(comboModel);
        cmbFamilias.setRenderer(new FamiliaComboBoxRenderer()); 
        return cmbFamilias;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHogares = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtidHogar = new javax.swing.JTextField();
        BUSCAR = new javax.swing.JButton();
        AÑADIR = new javax.swing.JButton();
        MODIFICAR = new javax.swing.JButton();
        ELIMINAR = new javax.swing.JButton();
        VER_FAMILIA = new javax.swing.JButton();
        VER_POSTULADOS = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        ACT_LISTA = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GESTOR HOGARES", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N
        setLayout(new java.awt.BorderLayout());

        tablaHogares.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaHogares);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setText("ID HOGAR");

        txtidHogar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        BUSCAR.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BUSCAR.setText("BUSCAR");
        BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCARActionPerformed(evt);
            }
        });

        AÑADIR.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        AÑADIR.setText("AÑADIR");
        AÑADIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AÑADIRActionPerformed(evt);
            }
        });

        MODIFICAR.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        MODIFICAR.setText("MODIFICAR");
        MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFICARActionPerformed(evt);
            }
        });

        ELIMINAR.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ELIMINAR.setText("ELIMINAR");
        ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ELIMINARActionPerformed(evt);
            }
        });

        VER_FAMILIA.setText("<html><center>VER POR<br>FAMILIA</center></html>");
        VER_FAMILIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VER_FAMILIAActionPerformed(evt);
            }
        });

        VER_POSTULADOS.setText("<html><center>VER <br>POSTULADOS</center></html>");
        VER_POSTULADOS.setAlignmentY(0.1F);
        VER_POSTULADOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VER_POSTULADOSActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        jLabel2.setText("LISTA HOGARES");

        ACT_LISTA.setText("<html><center>ACTUALIZAR <br>LISTA</center></html>");
        ACT_LISTA.setAlignmentY(0.1F);
        ACT_LISTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACT_LISTAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtidHogar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(AÑADIR, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MODIFICAR, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addComponent(VER_FAMILIA, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VER_POSTULADOS, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ACT_LISTA, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ACT_LISTA, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(VER_POSTULADOS)
                                .addComponent(VER_FAMILIA))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtidHogar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BUSCAR))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AÑADIR)
                            .addComponent(MODIFICAR)
                            .addComponent(ELIMINAR))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)))
                .addGap(0, 0, 0))
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void AÑADIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AÑADIRActionPerformed
        JTextField txtDireccion = new JTextField();
        JTextField txtCoords = new JTextField();
        JComboBox<Familia> cmbFamilias = crearComboFamiliasSinHogar(); 
        JPanel dialogPanel = new JPanel(new GridLayout(3, 2, 5, 5));
        dialogPanel.add(new JLabel("Direccion:"));
        dialogPanel.add(txtDireccion);
        dialogPanel.add(new JLabel("Coordenadas:"));
        dialogPanel.add(txtCoords);
        dialogPanel.add(new JLabel("Familia (Sin Hogar):"));
        dialogPanel.add(cmbFamilias);
        int result = JOptionPane.showConfirmDialog(this, dialogPanel, "Registrar Nuevo Hogar",JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            try {
                String direccion = txtDireccion.getText();
                String coords = txtCoords.getText();
                Familia familiaSel = (Familia) cmbFamilias.getSelectedItem();
                servicios.gestionHogares.registrarHogar(direccion, coords, familiaSel);
                JOptionPane.showMessageDialog(this, "Hogar postulado", "exito", JOptionPane.INFORMATION_MESSAGE);
                cargarDatosTabla(servicios.gestionHogares.listarHogares()); 
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al registrar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_AÑADIRActionPerformed

    private void MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFICARActionPerformed
        try {
            Hogar_Adopcion hogar = obtenerHogarDeTabla();
            JTextField txtDireccion = new JTextField(hogar.getDireccion());
            JTextField txtCoords = new JTextField(hogar.getCoordenadas());
            JPanel dialogPanel = new JPanel(new GridLayout(2, 2, 5, 5));
            dialogPanel.add(new JLabel("Direccion nueva:"));
            dialogPanel.add(txtDireccion);
            dialogPanel.add(new JLabel("Coordenadas:"));
            dialogPanel.add(txtCoords);

            int result = JOptionPane.showConfirmDialog(this, dialogPanel, "Modificar Hogar (ID: " + hogar.getIdhogarfam() + ")",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

            if (result == JOptionPane.OK_OPTION) {
                String nuevaDir = txtDireccion.getText();
                String nuevasCoords = txtCoords.getText();
                
                servicios.gestionHogares.modificarHogar(hogar, nuevaDir, nuevasCoords);
                
                JOptionPane.showMessageDialog(this, "Hogar actualizado.", "exito", JOptionPane.INFORMATION_MESSAGE);
                cargarDatosTabla(servicios.gestionHogares.listarHogares()); 
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al modificar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_MODIFICARActionPerformed

    private void ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ELIMINARActionPerformed
        try {
            Hogar_Adopcion hogar = obtenerHogarDeTabla();
            int confirm = JOptionPane.showConfirmDialog(this,"Seguro que deseas eliminar el hogar de la familia '" + hogar.getFamilia().getNombre() + "'?\n" +"(Solo si no tiene gatos asignados)","Confirmar Eliminacion", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (confirm == JOptionPane.YES_OPTION) {
                servicios.gestionHogares.eliminarHogar(hogar);
                JOptionPane.showMessageDialog(this, "Hogar eliminado.", "exito", JOptionPane.INFORMATION_MESSAGE);
                cargarDatosTabla(servicios.gestionHogares.listarHogares()); 
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ELIMINARActionPerformed

    private void BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSCARActionPerformed
        try {
            String idStr = txtidHogar.getText().trim();
            if (idStr.isEmpty()) throw new Exception("Ingrese un ID de Hogar.");
            int idHogar = Integer.parseInt(idStr);
            Hogar_Adopcion hogar = servicios.gestionHogares.buscarHogarPorId(idHogar);
                if (hogar != null) {
                    List<Hogar_Adopcion> lista = new ArrayList<>();
                    lista.add(hogar);
                    cargarDatosTabla(lista);
                } else {
                    JOptionPane.showMessageDialog(this, "No se encontro Hogar con ID: " + idHogar, "Error", JOptionPane.ERROR_MESSAGE);
                }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID invalido.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BUSCARActionPerformed

    private void VER_FAMILIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VER_FAMILIAActionPerformed
        try {
            List<Hogar_Adopcion> hogares = servicios.gestionHogares.listarHogares();
            if (hogares.isEmpty()) {return; }
            StringBuilder reporte = new StringBuilder();
            reporte.append("--- Reporte de Gatos por Familia ---\n\n");
            for (Hogar_Adopcion hogar : hogares) {
                Familia fam = hogar.getFamilia();
                reporte.append("Familia: " + (fam != null ? fam.getNombre() : "N/A") + " (Hogar ID: " + hogar.getIdhogarfam() + ")\n");
                List<Gato> gatos = hogar.getGatos(); 
                if (gatos == null || gatos.isEmpty()) {
                    reporte.append("  - Sin gatos asignados actualmente.\n");
                } else {
                    for (Gato gato : gatos) {
                        reporte.append("  - Gato: " + gato.getNombre() + " | Estado: " + gato.getAdoptado() + "\n");
                    }
                }
                reporte.append("----------------------------------\n");
            }
            JTextArea textArea = new JTextArea(reporte.toString());
            textArea.setEditable(false);
            JScrollPane scrollPane = new JScrollPane(textArea);
            scrollPane.setPreferredSize(new Dimension(600, 450)); 
            JOptionPane.showMessageDialog(this, scrollPane, "Gatos por Familia", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al generar reporte: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_VER_FAMILIAActionPerformed

    private void VER_POSTULADOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VER_POSTULADOSActionPerformed
        List<Hogar_Adopcion> postulados = servicios.gestionHogares.listarHogaresPostulados();
        cargarDatosTabla(postulados);
        txtidHogar.setText(""); 
    }//GEN-LAST:event_VER_POSTULADOSActionPerformed

    private void ACT_LISTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACT_LISTAActionPerformed
       cargarDatosTabla(servicios.gestionHogares.listarHogares());
        txtidHogar.setText(""); 
    }//GEN-LAST:event_ACT_LISTAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACT_LISTA;
    private javax.swing.JButton AÑADIR;
    private javax.swing.JButton BUSCAR;
    private javax.swing.JButton ELIMINAR;
    private javax.swing.JButton MODIFICAR;
    private javax.swing.JButton VER_FAMILIA;
    private javax.swing.JButton VER_POSTULADOS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaHogares;
    private javax.swing.JTextField txtidHogar;
    // End of variables declaration//GEN-END:variables
}
class FamiliaComboBoxRenderer extends javax.swing.plaf.basic.BasicComboBoxRenderer {
    @Override
    public java.awt.Component getListCellRendererComponent(
            javax.swing.JList list, Object value, int index,
            boolean isSelected, boolean cellHasFocus) {
        
        super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
        if (value instanceof Familia) {
            Familia fam = (Familia) value;
            setText(fam.getNombre() + " (DNI: " + fam.getDNI() + ")");
        } else if (value == null) { setText("Seleccione una familia"); }
        return this;
    }
}