/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Fabri
 */
import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Familia;
import modelo.Gato;
import modelo.Hogar_Adopcion;
import modelo.Usuario;
import servicio.Swingcontexto;

public class PanelFamilia extends javax.swing.JPanel {
    private Swingcontexto servicios;
    private Familia familiaLogueada;
    private Hogar_Adopcion miHogar; 
    private DefaultTableModel modeloTablaMisGatos;
    /**
     * Creates new form PanelFamilia
     */
    public PanelFamilia(Swingcontexto servicios, Usuario usuarioLogueado) {
        this.servicios = servicios;
        if (usuarioLogueado instanceof Familia) {
            this.familiaLogueada = (Familia) usuarioLogueado;
        } else {
             throw new RuntimeException("Panel Familia solo puede ser accedido por una Familia.");
        }
        initComponents();
        configurarTablaMisGatos();
        cargarDatosFamilia();
    }
        private void configurarTablaMisGatos() {
        modeloTablaMisGatos = new DefaultTableModel() {
            @Override public boolean isCellEditable(int row, int column) { return false; }
        };
        modeloTablaMisGatos.addColumn("ID Gato");
        modeloTablaMisGatos.addColumn("Nombre");
        modeloTablaMisGatos.addColumn("Color");
        modeloTablaMisGatos.addColumn("Estado Adopcion");
        tablaMisGatos.setModel(modeloTablaMisGatos);
    }
        private void cargarDatosFamilia() {
        this.miHogar = servicios.gestionHogares.buscarHogarPorFamilia(familiaLogueada);
        if (this.miHogar == null) {
            if (familiaLogueada.isPostulado()) {
                lblEstadoHogar.setText(" Aun no tienes un hogar registrado, pero tu solicitud de adopcion esta pendiente.");
                lblEstadoHogar.setForeground(java.awt.Color.BLUE);
            } else {
                lblEstadoHogar.setText(" Aun no has postulado un hogar ni solicitado una adopcion.");
                lblEstadoHogar.setForeground(java.awt.Color.RED);
            }
            cargarTablaMisGatos(new ArrayList<>()); 
            
        } else {
            String estado = miHogar.isAprobado() ? "APROBADO para adopcion definitiva" : "PENDIENTE (solo adopcion temporal)";
            lblEstadoHogar.setText("Estado de tu Hogar: " + estado);
            lblEstadoHogar.setForeground(miHogar.isAprobado() ? new java.awt.Color(0, 150, 0) : java.awt.Color.BLUE);
            cargarTablaMisGatos(miHogar.getGatos());
            txtDireccion.setText(miHogar.getDireccion());
            txtCoordenadas.setText(miHogar.getCoordenadas());
        }
    }
        private void cargarTablaMisGatos(List<Gato> gatos) {
        modeloTablaMisGatos.setRowCount(0);
        for (Gato gato : gatos) {
            Object[] fila = {
                gato.getId(),
                gato.getNombre(),
                gato.getColor(),
                gato.getAdoptado() 
            };
            modeloTablaMisGatos.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMihogar = new javax.swing.JPanel();
        lblEstadoHogar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCoordenadas = new javax.swing.JTextField();
        scrollMisGatos = new javax.swing.JScrollPane();
        tablaMisGatos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PANEL DE FAMILIA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N
        setLayout(new java.awt.BorderLayout());

        lblEstadoHogar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblEstadoHogar.setText("Estado");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Direccion :");

        txtDireccion.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel4.setText("Coordenadas :");

        txtCoordenadas.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        tablaMisGatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scrollMisGatos.setViewportView(tablaMisGatos);

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("Mis gatos");

        javax.swing.GroupLayout panelMihogarLayout = new javax.swing.GroupLayout(panelMihogar);
        panelMihogar.setLayout(panelMihogarLayout);
        panelMihogarLayout.setHorizontalGroup(
            panelMihogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMihogarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMihogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(panelMihogarLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(3, 3, 3)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(3, 3, 3)
                        .addComponent(txtCoordenadas, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblEstadoHogar))
                .addGap(0, 276, Short.MAX_VALUE))
            .addComponent(scrollMisGatos)
        );
        panelMihogarLayout.setVerticalGroup(
            panelMihogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMihogarLayout.createSequentialGroup()
                .addGroup(panelMihogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMihogarLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(panelMihogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCoordenadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(panelMihogarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblEstadoHogar)
                        .addGap(10, 10, 10)
                        .addGroup(panelMihogarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2)))
                .addComponent(scrollMisGatos, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(panelMihogar, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblEstadoHogar;
    private javax.swing.JPanel panelMihogar;
    private javax.swing.JScrollPane scrollMisGatos;
    private javax.swing.JTable tablaMisGatos;
    private javax.swing.JTextField txtCoordenadas;
    private javax.swing.JTextField txtDireccion;
    // End of variables declaration//GEN-END:variables
}
