/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Fabri
 */
import java.util.List;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import modelo.Usuario;
import modelo.Administrador;
import modelo.Veterinario;
import modelo.Voluntario;
import modelo.Familia;
import modelo.Sistema_reputacion;
import servicio.Swingcontexto;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField; // Para la clave
import java.awt.GridLayout;
import javax.swing.DefaultComboBoxModel;
import java.awt.event.ItemEvent;
import javax.swing.plaf.basic.BasicComboBoxRenderer;

public class PanelGestorUsuarios extends javax.swing.JPanel {
    private Swingcontexto servicios;
    private DefaultTableModel modeloTabla;
    /**
     * Creates new form PanelGestorUsuarios
     */
    public PanelGestorUsuarios(Swingcontexto servicios) {
        this.servicios = servicios;
        initComponents();
        configurarTabla();
        cargarRolComboBox(); 
        cargarDatosTabla(servicios.usuarioService.listarUsuarios());
        
    }
    private void configurarTabla() {
        modeloTabla = new DefaultTableModel() {
            @Override public boolean isCellEditable(int row, int column) { return false; }
        };
        
        modeloTabla.addColumn("DNI");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Rol");
        modeloTabla.addColumn("Telefono");
        modeloTabla.addColumn("Correo");
        modeloTabla.addColumn("Reputacion");
        
        tablaUsuarios.setModel(modeloTabla); 
    }
    private void cargarDatosTabla(List<Usuario> usuarios) {
        modeloTabla.setRowCount(0);
        for (Usuario u : usuarios) {
            String reputacionStr = "N/A";
            if (u instanceof Sistema_reputacion) {
                reputacionStr = String.valueOf(((Sistema_reputacion) u).getReputacion());
            }
            Object[] fila = {u.getDNI(),u.getNombre(),u.nombrerol(),u.getTelefono(), u.getCorreo(),reputacionStr};
            modeloTabla.addRow(fila);
        }
    }
        private void cargarRolComboBox(){
            DefaultComboBoxModel<String> comboModel = new DefaultComboBoxModel<>();
            comboModel.addElement("TODOS LOS ROLES"); 
            comboModel.addElement("Administrador"); 
            comboModel.addElement("Veterinario"); 
            comboModel.addElement("Voluntario"); 
            comboModel.addElement("Familia"); 

            rol.setRenderer(new RolComboBoxRenderer());
            rol.setModel(comboModel);
        }
        private Usuario obtenerUsuarioDeTabla() throws Exception {
         int filaSel = tablaUsuarios.getSelectedRow();
         if (filaSel == -1) {
             throw new Exception("Debe seleccionar un usuario de la tabla.");
         }
         String dni = (String) modeloTabla.getValueAt(filaSel, 0); 
         Usuario usuario = servicios.usuarioService.UsuarioporDNI(dni);
         if (usuario == null) {
             cargarDatosTabla(servicios.usuarioService.listarUsuarios()); 
             throw new Exception("El usuario seleccionado ya no existe. La tabla ha sido actualizada.");
         }
         return usuario;
    }
        private void limpiarFiltros() {
        txtIDUSUARIO.setText("");
        rol.setSelectedIndex(0);
    }

        
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtIDUSUARIO = new javax.swing.JTextField();
        MODIFICAR = new javax.swing.JButton();
        AÑADIR = new javax.swing.JButton();
        ELIMINAR = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rol = new javax.swing.JComboBox<>();
        REPUTACION = new javax.swing.JButton();
        ACTUALIZAR_LIST = new javax.swing.JButton();
        BUSCAR = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GESTOR DE USUARIOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 14))); // NOI18N
        setLayout(new java.awt.BorderLayout());

        jScrollPane1.setBackground(new java.awt.Color(255, 102, 102));

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaUsuarios);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel2.setPreferredSize(new java.awt.Dimension(895, 120));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ID USUARIO");

        txtIDUSUARIO.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        MODIFICAR.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        MODIFICAR.setText("MODIFICAR");
        MODIFICAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MODIFICARActionPerformed(evt);
            }
        });

        AÑADIR.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        AÑADIR.setText("AÑADIR");
        AÑADIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AÑADIRActionPerformed(evt);
            }
        });

        ELIMINAR.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ELIMINAR.setText("ELIMINAR");
        ELIMINAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ELIMINARActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("FILTRAR POR");

        rol.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        rol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ROL" }));
        rol.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rolItemStateChanged(evt);
            }
        });

        REPUTACION.setText("<html><center>MODIFICAR<br>REPUTACION</center></html>");
        REPUTACION.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REPUTACIONActionPerformed(evt);
            }
        });

        ACTUALIZAR_LIST.setText("<html><center>ACTUALIZAR<br>LISTA</center></html>");
        ACTUALIZAR_LIST.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACTUALIZAR_LISTActionPerformed(evt);
            }
        });

        BUSCAR.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        BUSCAR.setText("BUSCAR");
        BUSCAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BUSCARActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Lista de usuarios");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(txtIDUSUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BUSCAR, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(1, 1, 1)
                        .addComponent(rol, 0, 78, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(AÑADIR, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MODIFICAR, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ELIMINAR, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(12, 12, 12)
                .addComponent(REPUTACION, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ACTUALIZAR_LIST, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtIDUSUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(rol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BUSCAR))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AÑADIR)
                    .addComponent(MODIFICAR)
                    .addComponent(ELIMINAR))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ACTUALIZAR_LIST)
                    .addComponent(REPUTACION))
                .addContainerGap())
        );

        add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    private void MODIFICARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MODIFICARActionPerformed
        try {
            Usuario usuario = obtenerUsuarioDeTabla();
            JTextField txtNombre = new JTextField(usuario.getNombre());
            JPasswordField txtClave = new JPasswordField(usuario.getClave());
            JTextField txtTelefono = new JTextField(usuario.getTelefono());
            JTextField txtCorreo = new JTextField(usuario.getCorreo());
            JTextField txtMatricula = new JTextField();
            JLabel lblMatricula = new JLabel("Matricula (Veterinario):");
            JPanel dialogPanel = new JPanel(new GridLayout(5, 2, 5, 5));
            dialogPanel.add(new JLabel("Nombre Completo:"));
            dialogPanel.add(txtNombre);
            dialogPanel.add(new JLabel("Clave:"));
            dialogPanel.add(txtClave);
            dialogPanel.add(new JLabel("Telefono:"));
            dialogPanel.add(txtTelefono);
            dialogPanel.add(new JLabel("Correo:"));
            dialogPanel.add(txtCorreo);
            if (usuario instanceof Veterinario) {
                txtMatricula.setText(((Veterinario) usuario).getMatricula());
                dialogPanel.add(lblMatricula);
                dialogPanel.add(txtMatricula);
            }
            int result = JOptionPane.showConfirmDialog(this, dialogPanel, "Modificar Usuario (DNI: " + usuario.getDNI() + ")",
                    JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
            if (result == JOptionPane.OK_OPTION) {
                String nom = txtNombre.getText();
                String clave = new String(txtClave.getPassword());
                String tel = txtTelefono.getText();
                String correo = txtCorreo.getText();
                String mat = (usuario instanceof Veterinario) ? txtMatricula.getText() : null;
                servicios.usuarioService.modificarUsuario(usuario, nom, correo, tel, clave, mat);
                JOptionPane.showMessageDialog(this, "Usuario actualizado.", "exito", JOptionPane.INFORMATION_MESSAGE);
                cargarDatosTabla(servicios.usuarioService.listarUsuarios()); 
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al modificar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_MODIFICARActionPerformed

    private void AÑADIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AÑADIRActionPerformed
        JTextField txtDNI = new JTextField();
        JTextField txtNombre = new JTextField();
        JPasswordField txtClave = new JPasswordField();
        JTextField txtTelefono = new JTextField();
        JTextField txtCorreo = new JTextField();
        JComboBox<String> cmbRolDialog = new JComboBox<>(new String[]{"Seleccione", "Administrador", "Veterinario", "Voluntario", "Familia"});
        JTextField txtMatricula = new JTextField();
        JLabel lblMatricula = new JLabel("Matricula (Veterinario):");

        JPanel dialogPanel = new JPanel(new GridLayout(7, 2, 5, 5));
        dialogPanel.add(new JLabel("DNI:"));
        dialogPanel.add(txtDNI);
        dialogPanel.add(new JLabel("Nombre Completo:"));
        dialogPanel.add(txtNombre);
        dialogPanel.add(new JLabel("Clave:"));
        dialogPanel.add(txtClave);
        dialogPanel.add(new JLabel("Telefono:"));
        dialogPanel.add(txtTelefono);
        dialogPanel.add(new JLabel("Correo:"));
        dialogPanel.add(txtCorreo);
        dialogPanel.add(new JLabel("Rol:"));
        dialogPanel.add(cmbRolDialog);
        dialogPanel.add(lblMatricula);
        dialogPanel.add(txtMatricula);
        lblMatricula.setVisible(false);
        txtMatricula.setVisible(false);
        cmbRolDialog.addItemListener(e -> {
            if (e.getStateChange() == ItemEvent.SELECTED) {boolean esVet = e.getItem().equals("Veterinario");
                lblMatricula.setVisible(esVet);
                txtMatricula.setVisible(esVet);
            }
        });
        int result = JOptionPane.showConfirmDialog(this, dialogPanel, "Registrar Nuevo Usuario",JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            try {
                String dni = txtDNI.getText();
                String nombre = txtNombre.getText();
                String clave = new String(txtClave.getPassword());
                String tel = txtTelefono.getText();
                String correo = txtCorreo.getText();
                int rol = cmbRolDialog.getSelectedIndex(); 
                String matricula = txtMatricula.getText();
                if (rol == 0) throw new Exception("Debe seleccionar un rol.");
                servicios.usuarioService.registrar_usuario(dni, nombre, correo, tel, clave, rol, matricula);
                JOptionPane.showMessageDialog(this, "Usuario registrado con exito.", "exito", JOptionPane.INFORMATION_MESSAGE);
                cargarDatosTabla(servicios.usuarioService.listarUsuarios()); 
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error al registrar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_AÑADIRActionPerformed

    private void ELIMINARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ELIMINARActionPerformed
        try {
            Usuario usuario = obtenerUsuarioDeTabla();
            int confirm = JOptionPane.showConfirmDialog(this, 
                "Seguro que deseas eliminar al usuario '" + usuario.getNombre() + "' (DNI: " + usuario.getDNI() + ")?\n" +"Esta accion no se puede deshacer","Confirmar Eliminacion", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (confirm == JOptionPane.YES_OPTION) {
                servicios.usuarioService.eliminarUsuario(usuario);
                JOptionPane.showMessageDialog(this, "Usuario eliminado.", "exito", JOptionPane.INFORMATION_MESSAGE);
                cargarDatosTabla(servicios.usuarioService.listarUsuarios()); 
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al eliminar: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ELIMINARActionPerformed

    private void BUSCARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BUSCARActionPerformed
        try {
            if (rol.getSelectedIndex() != 0) {
                 throw new Exception("Limpia el filtro de Rol (pon 'TODOS') antes de buscar por ID.");
            }
            String idStr = txtIDUSUARIO.getText().trim();
            if (idStr.isEmpty()) {
                throw new Exception("ingrese un DNI para buscar.");
            }
            Usuario usuario = servicios.usuarioService.UsuarioporDNI(idStr); 
            if (usuario != null) {
                List<Usuario> listaBusqueda = new ArrayList<>();
                listaBusqueda.add(usuario);
                cargarDatosTabla(listaBusqueda); 
            } else {
                JOptionPane.showMessageDialog(this, "No se encontro ningun usuario con el DNI: " + idStr, "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "Error al Buscar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BUSCARActionPerformed

    private void REPUTACIONActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REPUTACIONActionPerformed
        try {
            Usuario usuario = obtenerUsuarioDeTabla();
            if (!(usuario instanceof Voluntario || usuario instanceof Familia)) {
                throw new Exception("Solo se puede modificar la reputacion de Voluntarios o Familias.");
            }
            Sistema_reputacion usuarioConRep = (Sistema_reputacion) usuario;
            String nuevoValorStr = JOptionPane.showInputDialog(this, "Ingrese el nuevo valor de reputacion para " + usuario.getNombre() + "\n(Actual: " + usuarioConRep.getReputacion() + "). Rango permitido: -1 a 3.","Modificar Reputacion",JOptionPane.QUESTION_MESSAGE);
            
            if (nuevoValorStr == null) return; 
            int nuevoValor = Integer.parseInt(nuevoValorStr);
            
                if(usuario instanceof Voluntario){
                servicios.usuarioService.modificarReputacionVoluntario(usuario, nuevoValor);
                }
                    if(usuario instanceof Familia){
                        servicios.usuarioService.modificarReputacionFamilia(usuario, nuevoValor);
                    }
                    JOptionPane.showMessageDialog(this, "Reputacion actualizada.", "exito", JOptionPane.INFORMATION_MESSAGE);
                    cargarDatosTabla(servicios.usuarioService.listarUsuarios()); 
        } catch (NumberFormatException e) {
             JOptionPane.showMessageDialog(this, "Valor invalido. Debe ser un numero.", "Error", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_REPUTACIONActionPerformed

    private void ACTUALIZAR_LISTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACTUALIZAR_LISTActionPerformed
        cargarDatosTabla(servicios.usuarioService.listarUsuarios());
        limpiarFiltros();
    }//GEN-LAST:event_ACTUALIZAR_LISTActionPerformed

    private void rolItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rolItemStateChanged
        if (evt.getStateChange() == ItemEvent.SELECTED) {
            if (!txtIDUSUARIO.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Limpia el campo 'ID USUARIO' antes de filtrar por rol.", "Error en busqueda", JOptionPane.WARNING_MESSAGE);
               rol.setSelectedIndex(0);
                cargarDatosTabla(servicios.usuarioService.listarUsuarios());
                return;
            }
            int rolSeleccionado = rol.getSelectedIndex(); 
            if (rolSeleccionado == 0) {
                cargarDatosTabla(servicios.usuarioService.listarUsuarios());
            } else {
                List<Usuario> todos = servicios.usuarioService.listarUsuarios();
                List<Usuario> filtrados = new ArrayList<>();
                for (Usuario u : todos) {
                    if (u.getRol() == rolSeleccionado) {
                        filtrados.add(u);
                    }
                }
                cargarDatosTabla(filtrados);
            }
        }
    }//GEN-LAST:event_rolItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACTUALIZAR_LIST;
    private javax.swing.JButton AÑADIR;
    private javax.swing.JButton BUSCAR;
    private javax.swing.JButton ELIMINAR;
    private javax.swing.JButton MODIFICAR;
    private javax.swing.JButton REPUTACION;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> rol;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txtIDUSUARIO;
    // End of variables declaration//GEN-END:variables
}
class RolComboBoxRenderer extends javax.swing.plaf.basic.BasicComboBoxRenderer {
    @Override
    public java.awt.Component getListCellRendererComponent(
            javax.swing.JList list, Object value, int index,
            boolean isSelected, boolean cellHasFocus) {
        super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
        if (value instanceof String) {
             setText(value.toString().toUpperCase()); 
        }
        return this;
    }
}
