/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Fabri
 */
import java.awt.GridLayout;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import modelo.Familia;
import modelo.Gato;
import modelo.Usuario;
import servicio.Swingcontexto;
import java.awt.BorderLayout;
import javax.swing.JLabel;

public class VerGatosFamilia extends javax.swing.JPanel {
    private Swingcontexto servicios;
    private Familia familiaLogueada;
    private JButton btnRefrescar;
    /**
     * Creates new form VerGatosFamilia
     */
    public VerGatosFamilia(Swingcontexto servicios, Usuario usuarioLogueado) {
        this.servicios = servicios;
        this.familiaLogueada = (Familia) usuarioLogueado;
        initComponents();
        gridPanel.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 10, 10));
        btnRefrescar = new JButton("Actualizar gatos disponibles");
        btnRefrescar.addActionListener(e -> cargarGatos());
        add(btnRefrescar, BorderLayout.NORTH);
        cargarGatos();
    }
    private void cargarGatos() {
        try {
            gridPanel.removeAll();
            List<Gato> gatosDisponibles = servicios.gatoService.listarGatosDisponibles();

            if (gatosDisponibles.isEmpty()) {
                gridPanel.add(new JLabel("No hay gatos disponibles para adopcion en este momento."));
            } else {
                for (Gato g : gatosDisponibles) {
                    TarjetaGato card = new TarjetaGato(g, familiaLogueada, servicios);
                    gridPanel.add(card);
                }
            }
            gridPanel.revalidate();
            gridPanel.repaint();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar gatos: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        gridPanel = new javax.swing.JPanel();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PERFILES DE GATOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 24))); // NOI18N
        setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout gridPanelLayout = new javax.swing.GroupLayout(gridPanel);
        gridPanel.setLayout(gridPanelLayout);
        gridPanelLayout.setHorizontalGroup(
            gridPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 905, Short.MAX_VALUE)
        );
        gridPanelLayout.setVerticalGroup(
            gridPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 572, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(gridPanel);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel gridPanel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
