/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Fabri
 */
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import modelo.SolicitudAdopcion;
import modelo.Usuario;
import servicio.Swingcontexto;
import java.time.format.DateTimeFormatter;
import java.awt.BorderLayout; 
import java.awt.FlowLayout;

public class VerSolicitudes extends javax.swing.JPanel {
    private Swingcontexto servicios;
    private Usuario usuarioLogueado;
    private DefaultTableModel modeloTabla;
    private static final DateTimeFormatter FORMATO_FECHA = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");
    /**
     * Creates new form VerSolicitudes
     */
    public VerSolicitudes(Swingcontexto servicios, Usuario usuarioLogueado) {
        this.servicios = servicios;
        this.usuarioLogueado = usuarioLogueado;
        initComponents();
        configurarTabla();
        cargarDatosTabla(servicios.adopcionService.verPendientes());
    }
    private void configurarTabla() {
        modeloTabla = new DefaultTableModel() {
            @Override public boolean isCellEditable(int row, int column) { return false; }
        };
        
        modeloTabla.addColumn("ID Solicitud");
        modeloTabla.addColumn("Fecha");
        modeloTabla.addColumn("Gato (ID)");
        modeloTabla.addColumn("Familia (DNI)");
        modeloTabla.addColumn("Estado");
        tablaSolicitudes.setModel(modeloTabla);
    }
    private void cargarDatosTabla(List<SolicitudAdopcion> solicitudes) {
        modeloTabla.setRowCount(0);
        for (SolicitudAdopcion s : solicitudes) {
            Object[] fila = {s.getIdSolicitud(),(s.getFechaSolicitud() != null) ? s.getFechaSolicitud().format(FORMATO_FECHA) : "N/A",(s.getGato() != null) ? s.getGato().getNombre() + " (ID:" + s.getGato().getId() + ")" : "N/A",(s.getFamilia() != null) ? s.getFamilia().getNombre() + " (DNI:" + s.getFamilia().getDNI() + ")" : "N/A",s.getEstadoComoTexto() };
            modeloTabla.addRow(fila);
        }
    }
    private SolicitudAdopcion obtenerSolicitudDeTabla() throws Exception {
         int filaSel = tablaSolicitudes.getSelectedRow();
         if (filaSel == -1) {
             throw new Exception("Debe seleccionar una solicitud de la tabla.");
         }
         int idSol = (int) modeloTabla.getValueAt(filaSel, 0); 
         SolicitudAdopcion solicitud = servicios.adopcionService.solicitudPorId(idSol);
         if (solicitud == null) {
             cargarDatosTabla(servicios.adopcionService.verPendientes()); 
             throw new Exception("La solicitud seleccionada ya no existe.");
         }
         return solicitud;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        ACEPTAR = new javax.swing.JButton();
        RECHAZAR = new javax.swing.JButton();
        ACT = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaSolicitudes = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SOLICITUDES PENDIENTES", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 18))); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(902, 50));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 892, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 19, Short.MAX_VALUE)
        );

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setPreferredSize(new java.awt.Dimension(150, 559));

        ACEPTAR.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ACEPTAR.setText("ACEPTAR");
        ACEPTAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACEPTARActionPerformed(evt);
            }
        });

        RECHAZAR.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        RECHAZAR.setText("RECHAZAR");
        RECHAZAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RECHAZARActionPerformed(evt);
            }
        });

        ACT.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        ACT.setText("ACTUALIZAR");
        ACT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ACTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ACT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RECHAZAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ACEPTAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ACEPTAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RECHAZAR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ACT)
                .addContainerGap(451, Short.MAX_VALUE))
        );

        add(jPanel2, java.awt.BorderLayout.LINE_START);

        tablaSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaSolicitudes);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void ACEPTARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACEPTARActionPerformed
        try {
            SolicitudAdopcion sol = obtenerSolicitudDeTabla();
            String[] opciones = {"Temporal (Hogar no Aprobado)", "Definitiva (Hogar Aprobado)"};
            int seleccion = JOptionPane.showOptionDialog(this, "Seleccione el tipo de aprobacion para la solicitud #" + sol.getIdSolicitud() +"\n(Familia: " + sol.getFamilia().getNombre() + ")", "Confirmar Aprobacion", JOptionPane.DEFAULT_OPTION,JOptionPane.QUESTION_MESSAGE,null,opciones, opciones[0]);
            int tipoAdopcion = -1;
            if (seleccion == 0) tipoAdopcion = 1; 
            if (seleccion == 1) tipoAdopcion = 2; 
            if (tipoAdopcion == -1) {
                JOptionPane.showMessageDialog(this, "Accion cancelada.", "Cancelado", JOptionPane.INFORMATION_MESSAGE);
                return; 
            }
            servicios.adopcionService.aprobarSolicitud(sol, tipoAdopcion); 
            JOptionPane.showMessageDialog(this, "Solicitud APROBADA.", "exito", JOptionPane.INFORMATION_MESSAGE);
            cargarDatosTabla(servicios.adopcionService.verPendientes());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error al Aprobar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ACEPTARActionPerformed

    private void RECHAZARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RECHAZARActionPerformed
        try {
            SolicitudAdopcion sol = obtenerSolicitudDeTabla();
            int confirm = JOptionPane.showConfirmDialog(this,"Seguro que deseas rechazar esta solicitud?","Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (confirm == JOptionPane.YES_OPTION) {
                servicios.adopcionService.rechazarSolicitud(sol);
                JOptionPane.showMessageDialog(this, "Solicitud rechazada. El gato vuelve a estar disponible.", "exito", JOptionPane.INFORMATION_MESSAGE);
                 cargarDatosTabla(servicios.adopcionService.verPendientes());
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error al Rechazar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_RECHAZARActionPerformed

    private void ACTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ACTActionPerformed
         cargarDatosTabla(servicios.adopcionService.verPendientes());
    }//GEN-LAST:event_ACTActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ACEPTAR;
    private javax.swing.JButton ACT;
    private javax.swing.JButton RECHAZAR;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaSolicitudes;
    // End of variables declaration//GEN-END:variables
}
